package main

// Code generated by generate.go. DO NOT EDIT.

type interfaceImplementation struct{}

func (interfaceImplementation) Print(int) { panic("not implemented") }

func (interfaceImplementation) Add(float64, float64) int { panic("not implemented") }

func (interfaceImplementation) Transform(float64) (error, []string) { panic("not implemented") }
