package main

// Code generated by generate.go. DO NOT EDIT.

type IntOpsImpMock struct {
	imp *IntOpsImp
}

type IntOpsImp struct {
	Mock     *IntOpsImpMock
	callChan chan *IntOpsImpCall
}

type IntOpsImpAddCall struct {
	responseChan chan IntOpsImpAddCallResponse
	A            int
	B            int
}

type IntOpsImpAddCallResponse struct {
	Type       string // "return", "panic", or "resolve"
	Result0    int
	PanicValue interface{}
}

func (c *IntOpsImpAddCall) InjectResult(result int) {
	c.responseChan <- IntOpsImpAddCallResponse{Type: "return", Result0: result}
}
func (c *IntOpsImpAddCall) InjectPanic(msg interface{}) {
	c.responseChan <- IntOpsImpAddCallResponse{Type: "panic", PanicValue: msg}
}

type IntOpsImpFormatCall struct {
	responseChan chan IntOpsImpFormatCallResponse
	Input        int
}

type IntOpsImpFormatCallResponse struct {
	Type       string // "return", "panic", or "resolve"
	Result0    string
	PanicValue interface{}
}

func (c *IntOpsImpFormatCall) InjectResult(result string) {
	c.responseChan <- IntOpsImpFormatCallResponse{Type: "return", Result0: result}
}
func (c *IntOpsImpFormatCall) InjectPanic(msg interface{}) {
	c.responseChan <- IntOpsImpFormatCallResponse{Type: "panic", PanicValue: msg}
}

type IntOpsImpPrintCall struct {
	responseChan chan IntOpsImpPrintCallResponse
	S            string
}

type IntOpsImpPrintCallResponse struct {
	Type       string // "return", "panic", or "resolve"
	PanicValue interface{}
}

func (c *IntOpsImpPrintCall) Resolve() {
	c.responseChan <- IntOpsImpPrintCallResponse{Type: "resolve"}
}
func (c *IntOpsImpPrintCall) InjectPanic(msg interface{}) {
	c.responseChan <- IntOpsImpPrintCallResponse{Type: "panic", PanicValue: msg}
}

func (m *IntOpsImpMock) Add(param0 int, param1 int) int {
	responseChan := make(chan IntOpsImpAddCallResponse, 1)

	call := &IntOpsImpAddCall{
		responseChan: responseChan,
		A:            param0,
		B:            param1,
	}

	callEvent := &IntOpsImpCall{
		Add: call,
	}

	m.imp.callChan <- callEvent

	resp := <-responseChan

	switch resp.Type {
	case "return":
		return resp.Result0
	case "panic":
		panic(resp.PanicValue)
	case "resolve":
		var zero0 int
		returnzero0
	}
	// Default: return zero values
	var zero0 int
	returnzero0
}

func (m *IntOpsImpMock) Format(param0 int) string {
	responseChan := make(chan IntOpsImpFormatCallResponse, 1)

	call := &IntOpsImpFormatCall{
		responseChan: responseChan,
		Input:        param0,
	}

	callEvent := &IntOpsImpCall{
		Format: call,
	}

	m.imp.callChan <- callEvent

	resp := <-responseChan

	switch resp.Type {
	case "return":
		return resp.Result0
	case "panic":
		panic(resp.PanicValue)
	case "resolve":
		var zero0 string
		returnzero0
	}
	// Default: return zero values
	var zero0 string
	returnzero0
}

func (m *IntOpsImpMock) Print(param0 string) {
	responseChan := make(chan IntOpsImpPrintCallResponse, 1)

	call := &IntOpsImpPrintCall{
		responseChan: responseChan,
		S:            param0,
	}

	callEvent := &IntOpsImpCall{
		Print: call,
	}

	m.imp.callChan <- callEvent

	resp := <-responseChan

	switch resp.Type {
	case "return":
	case "panic":
		panic(resp.PanicValue)
	case "resolve":
	}
}

type IntOpsImpCall struct {
	Add    *IntOpsImpAddCall
	Format *IntOpsImpFormatCall
	Print  *IntOpsImpPrintCall
}

func (c *IntOpsImpCall) Name() string { return "" }

func (c *IntOpsImpCall) AsAdd() *IntOpsImpAddCall { return c.Add }

func (c *IntOpsImpCall) AsFormat() *IntOpsImpFormatCall { return c.Format }

func (c *IntOpsImpCall) AsPrint() *IntOpsImpPrintCall { return c.Print }

func (i *IntOpsImp) GetCurrentCall() *IntOpsImpCall {
	return <-i.callChan
}

func NewIntOpsImp(t *testing.T) *IntOpsImp {
	imp := &IntOpsImp{
		callChan: make(chan *IntOpsImpCall, 1),
	}
	imp.Mock = &IntOpsImpMock{imp: imp}
	return imp
}
