// Code generated by impgen. DO NOT EDIT.

package generics_test

import (
	_reflect "reflect"

	generics "github.com/toejough/imptest/UAT/07-generics"
	_imptest "github.com/toejough/imptest/imptest"
)

// WrapProcessItemReturnsReturn holds the return values from the wrapped function.
type WrapProcessItemReturnsReturn[T any] struct {
	Result0 error
}

// WrapProcessItemWrapper wraps a function for testing.
type WrapProcessItemWrapper[T any] struct {
	*_imptest.CallableController[WrapProcessItemReturnsReturn[T]]
	callable func(generics.Repository[T], string, func(T) T) error
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (w *WrapProcessItemWrapper[T]) ExpectPanicEquals(expected any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, expected)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (w *WrapProcessItemWrapper[T]) ExpectPanicMatches(matcher any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, matcher)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (w *WrapProcessItemWrapper[T]) ExpectReturnsEqual(v0 error) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		if !_reflect.DeepEqual(w.Returned.Result0, v0) {
			w.T.Fatalf("expected return value 0 to be %v, got %v", v0, w.Returned.Result0)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (w *WrapProcessItemWrapper[T]) ExpectReturnsMatch(v0 any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(w.Returned.Result0, v0)
		if !ok {
			w.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// Start executes the wrapped function in a goroutine.
func (w *WrapProcessItemWrapper[T]) Start(repo generics.Repository[T], id string, transformer func(T) T) *WrapProcessItemWrapper[T] {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				w.PanicChan <- r
			}
		}()
		ret0 := w.callable(repo, id, transformer)
		w.ReturnChan <- WrapProcessItemReturnsReturn[T]{Result0: ret0}
	}()
	return w
}

// WrapProcessItem wraps a function for testing.
func WrapProcessItem[T any](t _imptest.TestReporter, fn func(generics.Repository[T], string, func(T) T) error) *WrapProcessItemWrapper[T] {
	return &WrapProcessItemWrapper[T]{
		CallableController: _imptest.NewCallableController[WrapProcessItemReturnsReturn[T]](t),
		callable:           fn,
	}
}
