// Code generated by impgen. DO NOT EDIT.

package basic_test

import (
	basic "github.com/toejough/imptest/UAT/01-basic-interface-mocking"
	_imptest "github.com/toejough/imptest/imptest"
)

// CustomOpsMock is the mock for Ops.
type CustomOpsMock struct {
	imp    *_imptest.Imp
	Add    *CustomOpsMockAddMethod
	Store  *CustomOpsMockStoreMethod
	Log    *CustomOpsMockLogMethod
	Notify *CustomOpsMockNotifyMethod
	Finish *_imptest.DependencyMethod
}

// Interface returns the Ops implementation that can be passed to code under test.
func (m *CustomOpsMock) Interface() basic.Ops {
	return &mockCustomOpsImpl{mock: m}
}

// CustomOpsMockAddArgs holds typed arguments for Add.
type CustomOpsMockAddArgs struct {
	A int
	B int
}

// CustomOpsMockAddCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type CustomOpsMockAddCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *CustomOpsMockAddCall) GetArgs() CustomOpsMockAddArgs {
	raw := c.RawArgs()
	return CustomOpsMockAddArgs{
		A: raw[0].(int),
		B: raw[1].(int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *CustomOpsMockAddCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// CustomOpsMockAddMethod wraps DependencyMethod with typed returns.
type CustomOpsMockAddMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *CustomOpsMockAddMethod) ExpectCalledWithExactly(a int, b int) *CustomOpsMockAddCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(a, b)
	return &CustomOpsMockAddCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *CustomOpsMockAddMethod) ExpectCalledWithMatches(matchers ...any) *CustomOpsMockAddCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &CustomOpsMockAddCall{DependencyCall: call}
}

// CustomOpsMockFinishCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type CustomOpsMockFinishCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *CustomOpsMockFinishCall) InjectReturnValues(result0 bool) {
	c.DependencyCall.InjectReturnValues(result0)
}

// CustomOpsMockLogArgs holds typed arguments for Log.
type CustomOpsMockLogArgs struct {
	Message string
}

// CustomOpsMockLogCall wraps DependencyCall with typed GetArgs.
type CustomOpsMockLogCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *CustomOpsMockLogCall) GetArgs() CustomOpsMockLogArgs {
	raw := c.RawArgs()
	return CustomOpsMockLogArgs{
		Message: raw[0].(string),
	}
}

// CustomOpsMockLogMethod wraps DependencyMethod with typed returns.
type CustomOpsMockLogMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *CustomOpsMockLogMethod) ExpectCalledWithExactly(message string) *CustomOpsMockLogCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(message)
	return &CustomOpsMockLogCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *CustomOpsMockLogMethod) ExpectCalledWithMatches(matchers ...any) *CustomOpsMockLogCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &CustomOpsMockLogCall{DependencyCall: call}
}

// CustomOpsMockNotifyArgs holds typed arguments for Notify.
type CustomOpsMockNotifyArgs struct {
	Message string
	Ids     []int
}

// CustomOpsMockNotifyCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type CustomOpsMockNotifyCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *CustomOpsMockNotifyCall) GetArgs() CustomOpsMockNotifyArgs {
	raw := c.RawArgs()
	return CustomOpsMockNotifyArgs{
		Message: raw[0].(string),
		Ids:     raw[1].([]int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *CustomOpsMockNotifyCall) InjectReturnValues(result0 bool) {
	c.DependencyCall.InjectReturnValues(result0)
}

// CustomOpsMockNotifyMethod wraps DependencyMethod with typed returns.
type CustomOpsMockNotifyMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *CustomOpsMockNotifyMethod) ExpectCalledWithExactly(message string, ids ...int) *CustomOpsMockNotifyCall {
	callArgs := []any{message}
	for _, v := range ids {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.ExpectCalledWithExactly(callArgs...)
	return &CustomOpsMockNotifyCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *CustomOpsMockNotifyMethod) ExpectCalledWithMatches(matchers ...any) *CustomOpsMockNotifyCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &CustomOpsMockNotifyCall{DependencyCall: call}
}

// CustomOpsMockStoreArgs holds typed arguments for Store.
type CustomOpsMockStoreArgs struct {
	Key   string
	Value any
}

// CustomOpsMockStoreCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type CustomOpsMockStoreCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *CustomOpsMockStoreCall) GetArgs() CustomOpsMockStoreArgs {
	raw := c.RawArgs()
	return CustomOpsMockStoreArgs{
		Key:   raw[0].(string),
		Value: raw[1].(any),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *CustomOpsMockStoreCall) InjectReturnValues(result0 int, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// CustomOpsMockStoreMethod wraps DependencyMethod with typed returns.
type CustomOpsMockStoreMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *CustomOpsMockStoreMethod) ExpectCalledWithExactly(key string, value any) *CustomOpsMockStoreCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(key, value)
	return &CustomOpsMockStoreCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *CustomOpsMockStoreMethod) ExpectCalledWithMatches(matchers ...any) *CustomOpsMockStoreCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &CustomOpsMockStoreCall{DependencyCall: call}
}

// MockCustomOps creates a new CustomOpsMock for testing.
func MockCustomOps(t _imptest.TestReporter) *CustomOpsMock {
	imp := _imptest.NewImp(t)
	return &CustomOpsMock{
		imp:    imp,
		Add:    &CustomOpsMockAddMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Add")},
		Store:  &CustomOpsMockStoreMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Store")},
		Log:    &CustomOpsMockLogMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Log")},
		Notify: &CustomOpsMockNotifyMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Notify")},
		Finish: _imptest.NewDependencyMethod(imp, "Finish"),
	}
}

// mockCustomOpsImpl implements basic.Ops.
type mockCustomOpsImpl struct {
	mock *CustomOpsMock
}

// Add implements basic.Ops.Add.
func (impl *mockCustomOpsImpl) Add(a int, b int) int {
	call := &_imptest.GenericCall{
		MethodName:   "Add",
		Args:         []any{a, b},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// Finish implements basic.Ops.Finish.
func (impl *mockCustomOpsImpl) Finish() bool {
	call := &_imptest.GenericCall{
		MethodName:   "Finish",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 bool
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(bool); ok {
			result1 = value
		}
	}

	return result1
}

// Log implements basic.Ops.Log.
func (impl *mockCustomOpsImpl) Log(message string) {
	call := &_imptest.GenericCall{
		MethodName:   "Log",
		Args:         []any{message},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Notify implements basic.Ops.Notify.
func (impl *mockCustomOpsImpl) Notify(message string, ids ...int) bool {
	callArgs := []any{message}
	for _, v := range ids {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Notify",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 bool
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(bool); ok {
			result1 = value
		}
	}

	return result1
}

// Store implements basic.Ops.Store.
func (impl *mockCustomOpsImpl) Store(key string, value any) (int, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Store",
		Args:         []any{key, value},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}
