// Code generated by impgen. DO NOT EDIT.
// impgen:hash:4642351b18ef80d0

package mockstruct_test

import (
	_imptest "github.com/toejough/imptest"
)

// CalculatorImp holds method wrappers for setting expectations on Calculator.
type CalculatorImp struct {
	Add   *CalculatorMockAddMethod
	Get   *_imptest.DependencyMethod
	Reset *_imptest.DependencyMethod
	Store *CalculatorMockStoreMethod
}

// CalculatorMockAddArgs holds typed arguments for Add.
type CalculatorMockAddArgs struct {
	A int
	B int
}

// CalculatorMockAddCall wraps DependencyCall with typed GetArgs and Return.
type CalculatorMockAddCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *CalculatorMockAddCall) GetArgs() CalculatorMockAddArgs {
	raw := c.RawArgs()
	return CalculatorMockAddArgs{
		A: raw[0].(int),
		B: raw[1].(int),
	}
}

// Return specifies the typed values the mock should return.
func (c *CalculatorMockAddCall) Return(result0 int) {
	c.DependencyCall.Return(result0)
}

// CalculatorMockAddMethod wraps DependencyMethod with typed returns.
type CalculatorMockAddMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *CalculatorMockAddMethod
}

// Expect waits for a call with exactly the specified arguments.
func (m *CalculatorMockAddMethod) Expect(a int, b int) *CalculatorMockAddCall {
	call := m.DependencyMethod.Expect(a, b)
	return &CalculatorMockAddCall{DependencyCall: call}
}

// Match waits for a call with arguments matching the given matchers.
func (m *CalculatorMockAddMethod) Match(matchers ...any) *CalculatorMockAddCall {
	call := m.DependencyMethod.Match(matchers...)
	return &CalculatorMockAddCall{DependencyCall: call}
}

// CalculatorMockGetCall wraps DependencyCall with typed GetArgs and Return.
type CalculatorMockGetCall struct {
	*_imptest.DependencyCall
}

// Return specifies the typed values the mock should return.
func (c *CalculatorMockGetCall) Return(result0 int, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

// CalculatorMockInterface is a generated interface matching the methods of Calculator.
type CalculatorMockInterface interface {
	Add(a int, b int) int
	Get() (int, error)
	Reset()
	Store(value int) int
}

// CalculatorMockStoreArgs holds typed arguments for Store.
type CalculatorMockStoreArgs struct {
	Value int
}

// CalculatorMockStoreCall wraps DependencyCall with typed GetArgs and Return.
type CalculatorMockStoreCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *CalculatorMockStoreCall) GetArgs() CalculatorMockStoreArgs {
	raw := c.RawArgs()
	return CalculatorMockStoreArgs{
		Value: raw[0].(int),
	}
}

// Return specifies the typed values the mock should return.
func (c *CalculatorMockStoreCall) Return(result0 int) {
	c.DependencyCall.Return(result0)
}

// CalculatorMockStoreMethod wraps DependencyMethod with typed returns.
type CalculatorMockStoreMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *CalculatorMockStoreMethod
}

// Expect waits for a call with exactly the specified arguments.
func (m *CalculatorMockStoreMethod) Expect(value int) *CalculatorMockStoreCall {
	call := m.DependencyMethod.Expect(value)
	return &CalculatorMockStoreCall{DependencyCall: call}
}

// Match waits for a call with arguments matching the given matchers.
func (m *CalculatorMockStoreMethod) Match(matchers ...any) *CalculatorMockStoreCall {
	call := m.DependencyMethod.Match(matchers...)
	return &CalculatorMockStoreCall{DependencyCall: call}
}

// MockCalculator creates a mock Calculator and returns (mock, expectation handle).
func MockCalculator(t _imptest.TestReporter) (CalculatorMockInterface, *CalculatorImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &CalculatorImp{
		Add:   newCalculatorMockAddMethod(_imptest.NewDependencyMethod(ctrl, "Add")),
		Get:   _imptest.NewDependencyMethod(ctrl, "Get"),
		Reset: _imptest.NewDependencyMethod(ctrl, "Reset"),
		Store: newCalculatorMockStoreMethod(_imptest.NewDependencyMethod(ctrl, "Store")),
	}
	mock := &mockCalculatorImpl{ctrl: ctrl}
	return mock, imp
}

// mockCalculatorImpl implements CalculatorMockInterface.
type mockCalculatorImpl struct {
	ctrl *_imptest.Imp
}

// Add implements Calculator.Add.
func (impl *mockCalculatorImpl) Add(a int, b int) int {
	call := &_imptest.GenericCall{
		MethodName:   "Add",
		Args:         []any{a, b},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// Get implements Calculator.Get.
func (impl *mockCalculatorImpl) Get() (int, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Get",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Reset implements Calculator.Reset.
func (impl *mockCalculatorImpl) Reset() {
	call := &_imptest.GenericCall{
		MethodName:   "Reset",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Store implements Calculator.Store.
func (impl *mockCalculatorImpl) Store(value int) int {
	call := &_imptest.GenericCall{
		MethodName:   "Store",
		Args:         []any{value},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// newCalculatorMockAddMethod creates a typed method wrapper with Eventually initialized.
func newCalculatorMockAddMethod(dm *_imptest.DependencyMethod) *CalculatorMockAddMethod {
	m := &CalculatorMockAddMethod{DependencyMethod: dm}
	m.Eventually = &CalculatorMockAddMethod{DependencyMethod: dm.Eventually}
	return m
}

// newCalculatorMockStoreMethod creates a typed method wrapper with Eventually initialized.
func newCalculatorMockStoreMethod(dm *_imptest.DependencyMethod) *CalculatorMockStoreMethod {
	m := &CalculatorMockStoreMethod{DependencyMethod: dm}
	m.Eventually = &CalculatorMockStoreMethod{DependencyMethod: dm.Eventually}
	return m
}
