// Code generated by impgen. DO NOT EDIT.

package timeconflict_test

import (
	time "github.com/toejough/imptest/UAT/11-package-name-conflicts/time"
	_imptest "github.com/toejough/imptest/imptest"
)

// TimerMock is the mock for Timer.
type TimerMock struct {
	imp        *_imptest.Imp
	Wait       *_imptest.DependencyMethod
	GetElapsed *_imptest.DependencyMethod
}

// Interface returns the Timer implementation that can be passed to code under test.
func (m *TimerMock) Interface() time.Timer {
	return &mockTimerImpl{mock: m}
}

// MockTimer creates a new TimerMock for testing.
func MockTimer(t _imptest.TestReporter) *TimerMock {
	imp := _imptest.NewImp(t)
	return &TimerMock{
		imp:        imp,
		Wait:       _imptest.NewDependencyMethod(imp, "Wait"),
		GetElapsed: _imptest.NewDependencyMethod(imp, "GetElapsed"),
	}
}

// mockTimerImpl implements time.Timer.
type mockTimerImpl struct {
	mock *TimerMock
}

// GetElapsed implements time.Timer.GetElapsed.
func (impl *mockTimerImpl) GetElapsed() int {
	call := &_imptest.GenericCall{
		MethodName:   "GetElapsed",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// Wait implements time.Timer.Wait.
func (impl *mockTimerImpl) Wait(seconds int) error {
	call := &_imptest.GenericCall{
		MethodName:   "Wait",
		Args:         []any{seconds},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
