// Code generated by impgen. DO NOT EDIT.

package timeconflict_test

import (
	time "time"

	timeconflict "github.com/toejough/imptest/UAT/11-package-name-conflicts"
	_imptest "github.com/toejough/imptest/imptest"
)

// SchedulerMock is the mock for Scheduler.
type SchedulerMock struct {
	imp         *_imptest.Imp
	ScheduleAt  *SchedulerMockScheduleAtMethod
	Delay       *SchedulerMockDelayMethod
	NextRun     *_imptest.DependencyMethod
	GetInterval *SchedulerMockGetIntervalMethod
}

// Interface returns the Scheduler implementation that can be passed to code under test.
func (m *SchedulerMock) Interface() timeconflict.Scheduler {
	return &mockSchedulerImpl{mock: m}
}

// SchedulerMockDelayArgs holds typed arguments for Delay.
type SchedulerMockDelayArgs struct {
	TaskID   string
	Duration time.Duration
}

// SchedulerMockDelayCall wraps DependencyCall with typed GetArgs.
type SchedulerMockDelayCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SchedulerMockDelayCall) GetArgs() SchedulerMockDelayArgs {
	raw := c.RawArgs()
	return SchedulerMockDelayArgs{
		TaskID:   raw[0].(string),
		Duration: raw[1].(time.Duration),
	}
}

// SchedulerMockDelayMethod wraps DependencyMethod with typed returns.
type SchedulerMockDelayMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SchedulerMockDelayMethod) ExpectCalledWithExactly(taskID string, duration time.Duration) *SchedulerMockDelayCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(taskID, duration)
	return &SchedulerMockDelayCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SchedulerMockDelayMethod) ExpectCalledWithMatches(matchers ...any) *SchedulerMockDelayCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SchedulerMockDelayCall{DependencyCall: call}
}

// SchedulerMockGetIntervalArgs holds typed arguments for GetInterval.
type SchedulerMockGetIntervalArgs struct {
	TaskID string
}

// SchedulerMockGetIntervalCall wraps DependencyCall with typed GetArgs.
type SchedulerMockGetIntervalCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SchedulerMockGetIntervalCall) GetArgs() SchedulerMockGetIntervalArgs {
	raw := c.RawArgs()
	return SchedulerMockGetIntervalArgs{
		TaskID: raw[0].(string),
	}
}

// SchedulerMockGetIntervalMethod wraps DependencyMethod with typed returns.
type SchedulerMockGetIntervalMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SchedulerMockGetIntervalMethod) ExpectCalledWithExactly(taskID string) *SchedulerMockGetIntervalCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(taskID)
	return &SchedulerMockGetIntervalCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SchedulerMockGetIntervalMethod) ExpectCalledWithMatches(matchers ...any) *SchedulerMockGetIntervalCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SchedulerMockGetIntervalCall{DependencyCall: call}
}

// SchedulerMockScheduleAtArgs holds typed arguments for ScheduleAt.
type SchedulerMockScheduleAtArgs struct {
	TaskID string
	When   time.Time
}

// SchedulerMockScheduleAtCall wraps DependencyCall with typed GetArgs.
type SchedulerMockScheduleAtCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SchedulerMockScheduleAtCall) GetArgs() SchedulerMockScheduleAtArgs {
	raw := c.RawArgs()
	return SchedulerMockScheduleAtArgs{
		TaskID: raw[0].(string),
		When:   raw[1].(time.Time),
	}
}

// SchedulerMockScheduleAtMethod wraps DependencyMethod with typed returns.
type SchedulerMockScheduleAtMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SchedulerMockScheduleAtMethod) ExpectCalledWithExactly(taskID string, when time.Time) *SchedulerMockScheduleAtCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(taskID, when)
	return &SchedulerMockScheduleAtCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SchedulerMockScheduleAtMethod) ExpectCalledWithMatches(matchers ...any) *SchedulerMockScheduleAtCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SchedulerMockScheduleAtCall{DependencyCall: call}
}

// MockScheduler creates a new SchedulerMock for testing.
func MockScheduler(t _imptest.TestReporter) *SchedulerMock {
	imp := _imptest.NewImp(t)
	return &SchedulerMock{
		imp:         imp,
		ScheduleAt:  &SchedulerMockScheduleAtMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "ScheduleAt")},
		Delay:       &SchedulerMockDelayMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Delay")},
		NextRun:     _imptest.NewDependencyMethod(imp, "NextRun"),
		GetInterval: &SchedulerMockGetIntervalMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "GetInterval")},
	}
}

// mockSchedulerImpl implements timeconflict.Scheduler.
type mockSchedulerImpl struct {
	mock *SchedulerMock
}

// Delay implements timeconflict.Scheduler.Delay.
func (impl *mockSchedulerImpl) Delay(taskID string, duration time.Duration) error {
	call := &_imptest.GenericCall{
		MethodName:   "Delay",
		Args:         []any{taskID, duration},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// GetInterval implements timeconflict.Scheduler.GetInterval.
func (impl *mockSchedulerImpl) GetInterval(taskID string) time.Duration {
	call := &_imptest.GenericCall{
		MethodName:   "GetInterval",
		Args:         []any{taskID},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 time.Duration
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(time.Duration); ok {
			result1 = value
		}
	}

	return result1
}

// NextRun implements timeconflict.Scheduler.NextRun.
func (impl *mockSchedulerImpl) NextRun() (time.Time, error) {
	call := &_imptest.GenericCall{
		MethodName:   "NextRun",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 time.Time
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(time.Time); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// ScheduleAt implements timeconflict.Scheduler.ScheduleAt.
func (impl *mockSchedulerImpl) ScheduleAt(taskID string, when time.Time) error {
	call := &_imptest.GenericCall{
		MethodName:   "ScheduleAt",
		Args:         []any{taskID, when},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
