// Code generated by impgen. DO NOT EDIT.
// impgen:hash:1dd448a051035771

package safety_test

import (
	_imptest "github.com/toejough/imptest"
	safety "github.com/toejough/imptest/UAT/variations/behavior/panic-handling"
)

type CriticalDependencyImp struct {
	DoWork *_imptest.DependencyMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *CriticalDependencyImpEventually
}

type CriticalDependencyImpEventually struct {
	DoWork *_imptest.DependencyMethod
}

// MockCriticalDependency creates a mock CriticalDependency and returns (mock, expectation handle).
func MockCriticalDependency(t _imptest.TestReporter) (safety.CriticalDependency, *CriticalDependencyImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &CriticalDependencyImp{
		DoWork: _imptest.NewDependencyMethod(ctrl, "DoWork"),
	}
	imp.Eventually = &CriticalDependencyImpEventually{
		DoWork: _imptest.NewDependencyMethod(ctrl, "DoWork").AsEventually(),
	}
	mock := &mockCriticalDependencyImpl{ctrl: ctrl}
	return mock, imp
}

type mockCriticalDependencyImpl struct {
	ctrl *_imptest.Imp
}

// DoWork implements safety.CriticalDependency.DoWork.
func (impl *mockCriticalDependencyImpl) DoWork() {
	call := &_imptest.GenericCall{
		MethodName:   "DoWork",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}
