// Code generated by impgen. DO NOT EDIT.
// impgen:hash:ad5f7bcd50940237

package safety_test

import (
	_imptest "github.com/toejough/imptest"
	safety "github.com/toejough/imptest/UAT/variations/behavior/panic-handling"
	_reflect "reflect"
)

// WrapSafeRunnerCallHandle represents a single call to the wrapped function.
type WrapSafeRunnerCallHandle struct {
	*_imptest.CallableController[WrapSafeRunnerReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapSafeRunnerCallHandleEventually
}

// ExpectPanic verifies the function panics with the expected value.
func (h *WrapSafeRunnerCallHandle) ExpectPanic(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatch verifies the function panics with a value matching the given matcher.
func (h *WrapSafeRunnerCallHandle) ExpectPanicMatch(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturn verifies the function returned the expected values.
func (h *WrapSafeRunnerCallHandle) ExpectReturn(v0 bool) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnMatch verifies the return values match the given matchers.
func (h *WrapSafeRunnerCallHandle) ExpectReturnMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapSafeRunnerCallHandleEventually wraps a call handle for async expectation registration.
type WrapSafeRunnerCallHandleEventually struct {
	h *WrapSafeRunnerCallHandle
}

// ExpectPanic registers an async expectation for a panic value.
func (e *WrapSafeRunnerCallHandleEventually) ExpectPanic(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ExpectReturn registers an async expectation for return values.
func (e *WrapSafeRunnerCallHandleEventually) ExpectReturn(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *WrapSafeRunnerCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapSafeRunnerReturnsReturn holds the return values from the wrapped function.
type WrapSafeRunnerReturnsReturn struct {
	Result0 bool
}

// WrapSafeRunnerWrapperHandle is the test handle for a wrapped function.
type WrapSafeRunnerWrapperHandle struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(safety.CriticalDependency) bool
}

// Start executes the wrapped function in a goroutine.
func (w *WrapSafeRunnerWrapperHandle) Start(dep safety.CriticalDependency) *WrapSafeRunnerCallHandle {
	handle := &WrapSafeRunnerCallHandle{
		CallableController: _imptest.NewCallableController[WrapSafeRunnerReturnsReturn](w.t),
		controller:         w.controller,
	}
	handle.Eventually = &WrapSafeRunnerCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := w.callable(dep)
		handle.ReturnChan <- WrapSafeRunnerReturnsReturn{Result0: ret0}
	}()
	return handle
}

// WrapSafeRunner wraps a function for testing.
func WrapSafeRunner(t _imptest.TestReporter, fn func(safety.CriticalDependency) bool) *WrapSafeRunnerWrapperHandle {
	return &WrapSafeRunnerWrapperHandle{
		t:          t,
		controller: _imptest.NewTargetController(t),
		callable:   fn,
	}
}
