// Code generated by impgen. DO NOT EDIT.
// impgen:hash:cc78e83762477eeb

package safety_test

import (
	_imptest "github.com/toejough/imptest"
	safety "github.com/toejough/imptest/UAT/variations/behavior/panic-handling"
)

// WrapUnsafeRunnerCallHandle represents a single call to the wrapped function.
type WrapUnsafeRunnerCallHandle struct {
	*_imptest.CallableController[WrapUnsafeRunnerReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapUnsafeRunnerCallHandleEventually
}

// ExpectCompletes verifies the function completes without panicking.
func (h *WrapUnsafeRunnerCallHandle) ExpectCompletes() {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		h.T.Fatalf("expected function to complete, but it panicked with: %v", h.Panicked)
	}
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapUnsafeRunnerCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapUnsafeRunnerCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// WrapUnsafeRunnerCallHandleEventually wraps a call handle for async expectation registration.
type WrapUnsafeRunnerCallHandleEventually struct {
	h *WrapUnsafeRunnerCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapUnsafeRunnerCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapUnsafeRunnerCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapUnsafeRunnerCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapUnsafeRunnerReturnsReturn holds the return values from the wrapped function.
type WrapUnsafeRunnerReturnsReturn struct {
}

// WrapUnsafeRunnerWrapperHandle is the test handle for a wrapped function.
type WrapUnsafeRunnerWrapperHandle struct {
	Method     *WrapUnsafeRunnerWrapperMethod
	Controller *_imptest.TargetController
}

// WrapUnsafeRunnerWrapperMethod wraps a function for testing.
type WrapUnsafeRunnerWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(safety.CriticalDependency)
}

// Start executes the wrapped function in a goroutine.
func (m *WrapUnsafeRunnerWrapperMethod) Start(dep safety.CriticalDependency) *WrapUnsafeRunnerCallHandle {
	handle := &WrapUnsafeRunnerCallHandle{
		CallableController: _imptest.NewCallableController[WrapUnsafeRunnerReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapUnsafeRunnerCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		m.callable(dep)
		handle.ReturnChan <- WrapUnsafeRunnerReturnsReturn{}
	}()
	return handle
}

// WrapUnsafeRunner wraps a function for testing.
func WrapUnsafeRunner(t _imptest.TestReporter, fn func(safety.CriticalDependency)) *WrapUnsafeRunnerWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapUnsafeRunnerWrapperHandle{
		Method: &WrapUnsafeRunnerWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
