// Code generated by impgen. DO NOT EDIT.

package externalfuncs_test

import (
	_imptest "github.com/toejough/imptest"
	http "net/http"
)

// WrapHandlerFuncCallHandle represents a single call to the wrapped function.
type WrapHandlerFuncCallHandle struct {
	*_imptest.CallableController[WrapHandlerFuncReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapHandlerFuncCallHandleEventually
}

// ExpectCompletes verifies the function completes without panicking.
func (h *WrapHandlerFuncCallHandle) ExpectCompletes() {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		h.T.Fatalf("expected function to complete, but it panicked with: %v", h.Panicked)
	}
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapHandlerFuncCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapHandlerFuncCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// WrapHandlerFuncCallHandleEventually wraps a call handle for async expectation registration.
type WrapHandlerFuncCallHandleEventually struct {
	h *WrapHandlerFuncCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapHandlerFuncCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapHandlerFuncCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapHandlerFuncCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapHandlerFuncReturnsReturn holds the return values from the wrapped function.
type WrapHandlerFuncReturnsReturn struct {
}

// WrapHandlerFuncWrapperHandle is the test handle for a wrapped function.
type WrapHandlerFuncWrapperHandle struct {
	Method     *WrapHandlerFuncWrapperMethod
	Controller *_imptest.TargetController
}

// WrapHandlerFuncWrapperMethod wraps a function for testing.
type WrapHandlerFuncWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(http.ResponseWriter, *http.Request)
}

// Start executes the wrapped function in a goroutine.
func (m *WrapHandlerFuncWrapperMethod) Start(arg1 http.ResponseWriter, arg2 *http.Request) *WrapHandlerFuncCallHandle {
	handle := &WrapHandlerFuncCallHandle{
		CallableController: _imptest.NewCallableController[WrapHandlerFuncReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapHandlerFuncCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		m.callable(arg1, arg2)
		handle.ReturnChan <- WrapHandlerFuncReturnsReturn{}
	}()
	return handle
}

// WrapHandlerFunc wraps a function for testing.
func WrapHandlerFunc(t _imptest.TestReporter, fn func(http.ResponseWriter, *http.Request)) *WrapHandlerFuncWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapHandlerFuncWrapperHandle{
		Method: &WrapHandlerFuncWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
