// Code generated by impgen. DO NOT EDIT.

package safety_test

import (
	safety "github.com/toejough/imptest/UAT/04-error-and-panic-handling"
	"github.com/toejough/imptest/imptest"
	"testing"
)

type SafeRunnerImpReturn struct {
	Result0 bool
}

type SafeRunnerImp struct {
	t        testing.TB
	callable func(dep safety.CriticalDependency) bool

	returnChan chan SafeRunnerImpReturn
	panicChan  chan any
	returned   *SafeRunnerImpReturn
	panicked   any
}

func NewSafeRunnerImp(t testing.TB, callable func(dep safety.CriticalDependency) bool) *SafeRunnerImp {
	return &SafeRunnerImp{
		t:          t,
		callable:   callable,
		returnChan: make(chan SafeRunnerImpReturn, 1),
		panicChan:  make(chan any, 1),
	}
}

func (s *SafeRunnerImp) Start(dep safety.CriticalDependency) *SafeRunnerImp {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				s.panicChan <- r
			}
		}()

		ret0 := s.callable(dep)
		s.returnChan <- SafeRunnerImpReturn{
			Result0: ret0,
		}
	}()
	return s
}

func (s *SafeRunnerImp) ExpectReturnedValuesAre(v1 bool) {
	s.t.Helper()

	// Check if we already have a return value or panic
	if s.returned != nil {
		if s.returned.Result0 != v1 {
			s.t.Fatalf("expected return value 0 to be %v, got %v", v1, s.returned.Result0)
		}
		return
	}

	if s.panicked != nil {
		s.t.Fatalf("expected function to return, but it panicked with: %v", s.panicked)
	}

	// Wait for either return or panic
	select {
	case ret := <-s.returnChan:
		s.returned = &ret
		if ret.Result0 != v1 {
			s.t.Fatalf("expected return value 0 to be %v, got %v", v1, ret.Result0)
		}
	case p := <-s.panicChan:
		s.panicked = p
		s.t.Fatalf("expected function to return, but it panicked with: %v", p)
	}
}

func (s *SafeRunnerImp) ExpectReturnedValuesShould(v1 any) {
	s.t.Helper()

	// Check if we already have a return value or panic
	if s.returned != nil {
		var ok bool
		var msg string
		ok, msg = imptest.MatchValue(s.returned.Result0, v1)
		if !ok {
			s.t.Fatalf("return value 0: %s", msg)
		}
		return
	}

	if s.panicked != nil {
		s.t.Fatalf("expected function to return, but it panicked with: %v", s.panicked)
	}

	// Wait for either return or panic
	select {
	case ret := <-s.returnChan:
		s.returned = &ret
		var ok bool
		var msg string
		ok, msg = imptest.MatchValue(ret.Result0, v1)
		if !ok {
			s.t.Fatalf("return value 0: %s", msg)
		}
	case p := <-s.panicChan:
		s.panicked = p
		s.t.Fatalf("expected function to return, but it panicked with: %v", p)
	}
}

func (s *SafeRunnerImp) ExpectPanicWith(expected any) {
	s.t.Helper()

	// Check if we already have a return value or panic
	if s.panicked != nil {
		ok, msg := imptest.MatchValue(s.panicked, expected)
		if !ok {
			s.t.Fatalf("panic value: %s", msg)
		}
		return
	}

	if s.returned != nil {
		s.t.Fatalf("expected function to panic, but it returned")
	}

	// Wait for either return or panic
	select {
	case ret := <-s.returnChan:
		s.returned = &ret
		s.t.Fatalf("expected function to panic, but it returned")
	case p := <-s.panicChan:
		s.panicked = p
		ok, msg := imptest.MatchValue(p, expected)
		if !ok {
			s.t.Fatalf("panic value: %s", msg)
		}
	}
}

type SafeRunnerImpResponse struct {
	EventType string // "return" or "panic"
	ReturnVal *SafeRunnerImpReturn
	PanicVal  any
}

func (r *SafeRunnerImpResponse) Type() string {
	return r.EventType
}

func (r *SafeRunnerImpResponse) AsReturn() []any {
	if r.ReturnVal == nil {
		return nil
	}
	return []any{r.ReturnVal.Result0}
}

func (s *SafeRunnerImp) GetResponse() *SafeRunnerImpResponse {
	// Check if we already have a return value or panic
	if s.returned != nil {
		return &SafeRunnerImpResponse{
			EventType: "ReturnEvent",
			ReturnVal: s.returned,
		}
	}

	if s.panicked != nil {
		return &SafeRunnerImpResponse{
			EventType: "PanicEvent",
			PanicVal:  s.panicked,
		}
	}

	// Wait for either return or panic
	select {
	case ret := <-s.returnChan:
		s.returned = &ret
		return &SafeRunnerImpResponse{
			EventType: "ReturnEvent",
			ReturnVal: &ret,
		}
	case p := <-s.panicChan:
		s.panicked = p
		return &SafeRunnerImpResponse{
			EventType: "PanicEvent",
			PanicVal:  p,
		}
	}
}
