// Code generated by impgen. DO NOT EDIT.

package noncomparable_test

import (
	noncomparable "github.com/toejough/imptest/UAT/variations/signature/non-comparable"
	_imptest "github.com/toejough/imptest/imptest"
)

// DataProcessorMockHandle is the test handle for DataProcessor.
type DataProcessorMockHandle struct {
	Mock       noncomparable.DataProcessor
	Method     *DataProcessorMockMethods
	Controller *_imptest.Imp
}

// DataProcessorMockMethods holds method wrappers for setting expectations.
type DataProcessorMockMethods struct {
	ProcessSlice *DataProcessorMockProcessSliceMethod
	ProcessMap   *DataProcessorMockProcessMapMethod
}

// DataProcessorMockProcessMapArgs holds typed arguments for ProcessMap.
type DataProcessorMockProcessMapArgs struct {
	Config map[string]int
}

// DataProcessorMockProcessMapCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type DataProcessorMockProcessMapCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *DataProcessorMockProcessMapCall) GetArgs() DataProcessorMockProcessMapArgs {
	raw := c.RawArgs()
	return DataProcessorMockProcessMapArgs{
		Config: raw[0].(map[string]int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *DataProcessorMockProcessMapCall) InjectReturnValues(result0 bool) {
	c.DependencyCall.InjectReturnValues(result0)
}

// DataProcessorMockProcessMapMethod wraps DependencyMethod with typed returns.
type DataProcessorMockProcessMapMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *DataProcessorMockProcessMapMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *DataProcessorMockProcessMapMethod) ExpectCalledWithExactly(config map[string]int) *DataProcessorMockProcessMapCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(config)
	return &DataProcessorMockProcessMapCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *DataProcessorMockProcessMapMethod) ExpectCalledWithMatches(matchers ...any) *DataProcessorMockProcessMapCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &DataProcessorMockProcessMapCall{DependencyCall: call}
}

// DataProcessorMockProcessSliceArgs holds typed arguments for ProcessSlice.
type DataProcessorMockProcessSliceArgs struct {
	Data []string
}

// DataProcessorMockProcessSliceCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type DataProcessorMockProcessSliceCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *DataProcessorMockProcessSliceCall) GetArgs() DataProcessorMockProcessSliceArgs {
	raw := c.RawArgs()
	return DataProcessorMockProcessSliceArgs{
		Data: raw[0].([]string),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *DataProcessorMockProcessSliceCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// DataProcessorMockProcessSliceMethod wraps DependencyMethod with typed returns.
type DataProcessorMockProcessSliceMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *DataProcessorMockProcessSliceMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *DataProcessorMockProcessSliceMethod) ExpectCalledWithExactly(data []string) *DataProcessorMockProcessSliceCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(data)
	return &DataProcessorMockProcessSliceCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *DataProcessorMockProcessSliceMethod) ExpectCalledWithMatches(matchers ...any) *DataProcessorMockProcessSliceCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &DataProcessorMockProcessSliceCall{DependencyCall: call}
}

// MockDataProcessor creates a new DataProcessorMockHandle for testing.
func MockDataProcessor(t _imptest.TestReporter) *DataProcessorMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &DataProcessorMockMethods{
		ProcessSlice: newDataProcessorMockProcessSliceMethod(_imptest.NewDependencyMethod(ctrl, "ProcessSlice")),
		ProcessMap:   newDataProcessorMockProcessMapMethod(_imptest.NewDependencyMethod(ctrl, "ProcessMap")),
	}
	h := &DataProcessorMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockDataProcessorImpl{handle: h}
	return h
}

// mockDataProcessorImpl implements noncomparable.DataProcessor.
type mockDataProcessorImpl struct {
	handle *DataProcessorMockHandle
}

// ProcessMap implements noncomparable.DataProcessor.ProcessMap.
func (impl *mockDataProcessorImpl) ProcessMap(config map[string]int) bool {
	call := &_imptest.GenericCall{
		MethodName:   "ProcessMap",
		Args:         []any{config},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 bool
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(bool); ok {
			result1 = value
		}
	}

	return result1
}

// ProcessSlice implements noncomparable.DataProcessor.ProcessSlice.
func (impl *mockDataProcessorImpl) ProcessSlice(data []string) int {
	call := &_imptest.GenericCall{
		MethodName:   "ProcessSlice",
		Args:         []any{data},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// newDataProcessorMockProcessMapMethod creates a typed method wrapper with Eventually initialized.
func newDataProcessorMockProcessMapMethod(dm *_imptest.DependencyMethod) *DataProcessorMockProcessMapMethod {
	m := &DataProcessorMockProcessMapMethod{DependencyMethod: dm}
	m.Eventually = &DataProcessorMockProcessMapMethod{DependencyMethod: dm.Eventually}
	return m
}

// newDataProcessorMockProcessSliceMethod creates a typed method wrapper with Eventually initialized.
func newDataProcessorMockProcessSliceMethod(dm *_imptest.DependencyMethod) *DataProcessorMockProcessSliceMethod {
	m := &DataProcessorMockProcessSliceMethod{DependencyMethod: dm}
	m.Eventually = &DataProcessorMockProcessSliceMethod{DependencyMethod: dm.Eventually}
	return m
}
