// Code generated by impgen. DO NOT EDIT.
// impgen:hash:a23870d5bbcb7baf

package mockmethod_test

import (
	_imptest "github.com/toejough/imptest"
)

// CounterIncMockCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type CounterIncMockCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *CounterIncMockCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// MockCounterInc creates a mock Counter.Inc function and returns (mock, expectation handle).
func MockCounterInc(t _imptest.TestReporter) (func() int, *_imptest.DependencyMethod) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := _imptest.NewDependencyMethod(ctrl, "Counter.Inc")
	mock := func() int {
		call := &_imptest.GenericCall{
			MethodName:   "Counter.Inc",
			Args:         []any{},
			ResponseChan: make(chan _imptest.GenericResponse, 1),
		}
		ctrl.CallChan <- call
		resp := <-call.ResponseChan
		if resp.Type == "panic" {
			panic(resp.PanicValue)
		}

		var result1 int
		if len(resp.ReturnValues) > 0 {
			if value, ok := resp.ReturnValues[0].(int); ok {
				result1 = value
			}
		}

		return result1
	}
	return mock, imp
}
