// Code generated by impgen. DO NOT EDIT.
// impgen:hash:ac83195b69ac7de7

package concurrency_test

import (
	_imptest "github.com/toejough/imptest"
	concurrency "github.com/toejough/imptest/UAT/variations/concurrency/eventually"
)

// SlowServiceImp holds method wrappers for setting expectations on SlowService.
type SlowServiceImp struct {
	DoA *SlowServiceMockDoAMethod
	DoB *SlowServiceMockDoBMethod
}

// SlowServiceMockDoAArgs holds typed arguments for DoA.
type SlowServiceMockDoAArgs struct {
	Id int
}

// SlowServiceMockDoACall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SlowServiceMockDoACall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SlowServiceMockDoACall) GetArgs() SlowServiceMockDoAArgs {
	raw := c.RawArgs()
	return SlowServiceMockDoAArgs{
		Id: raw[0].(int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SlowServiceMockDoACall) InjectReturnValues(result0 string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// SlowServiceMockDoAMethod wraps DependencyMethod with typed returns.
type SlowServiceMockDoAMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *SlowServiceMockDoAMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SlowServiceMockDoAMethod) ExpectCalledWithExactly(id int) *SlowServiceMockDoACall {
	call := m.DependencyMethod.ExpectCalledWithExactly(id)
	return &SlowServiceMockDoACall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SlowServiceMockDoAMethod) ExpectCalledWithMatches(matchers ...any) *SlowServiceMockDoACall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SlowServiceMockDoACall{DependencyCall: call}
}

// SlowServiceMockDoBArgs holds typed arguments for DoB.
type SlowServiceMockDoBArgs struct {
	Id int
}

// SlowServiceMockDoBCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SlowServiceMockDoBCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SlowServiceMockDoBCall) GetArgs() SlowServiceMockDoBArgs {
	raw := c.RawArgs()
	return SlowServiceMockDoBArgs{
		Id: raw[0].(int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SlowServiceMockDoBCall) InjectReturnValues(result0 string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// SlowServiceMockDoBMethod wraps DependencyMethod with typed returns.
type SlowServiceMockDoBMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *SlowServiceMockDoBMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SlowServiceMockDoBMethod) ExpectCalledWithExactly(id int) *SlowServiceMockDoBCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(id)
	return &SlowServiceMockDoBCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SlowServiceMockDoBMethod) ExpectCalledWithMatches(matchers ...any) *SlowServiceMockDoBCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SlowServiceMockDoBCall{DependencyCall: call}
}

// MockSlowService creates a mock SlowService and returns (mock, expectation handle).
func MockSlowService(t _imptest.TestReporter) (concurrency.SlowService, *SlowServiceImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &SlowServiceImp{
		DoA: newSlowServiceMockDoAMethod(_imptest.NewDependencyMethod(ctrl, "DoA")),
		DoB: newSlowServiceMockDoBMethod(_imptest.NewDependencyMethod(ctrl, "DoB")),
	}
	mock := &mockSlowServiceImpl{ctrl: ctrl}
	return mock, imp
}

// mockSlowServiceImpl implements concurrency.SlowService.
type mockSlowServiceImpl struct {
	ctrl *_imptest.Imp
}

// DoA implements concurrency.SlowService.DoA.
func (impl *mockSlowServiceImpl) DoA(id int) string {
	call := &_imptest.GenericCall{
		MethodName:   "DoA",
		Args:         []any{id},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}

// DoB implements concurrency.SlowService.DoB.
func (impl *mockSlowServiceImpl) DoB(id int) string {
	call := &_imptest.GenericCall{
		MethodName:   "DoB",
		Args:         []any{id},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}

// newSlowServiceMockDoAMethod creates a typed method wrapper with Eventually initialized.
func newSlowServiceMockDoAMethod(dm *_imptest.DependencyMethod) *SlowServiceMockDoAMethod {
	m := &SlowServiceMockDoAMethod{DependencyMethod: dm}
	m.Eventually = &SlowServiceMockDoAMethod{DependencyMethod: dm.Eventually}
	return m
}

// newSlowServiceMockDoBMethod creates a typed method wrapper with Eventually initialized.
func newSlowServiceMockDoBMethod(dm *_imptest.DependencyMethod) *SlowServiceMockDoBMethod {
	m := &SlowServiceMockDoBMethod{DependencyMethod: dm}
	m.Eventually = &SlowServiceMockDoBMethod{DependencyMethod: dm.Eventually}
	return m
}
