// Code generated by impgen. DO NOT EDIT.

package visitor_test

import (
	visitor "github.com/toejough/imptest/UAT/variations/behavior/callbacks"
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapCountFilesCallHandle represents a single call to the wrapped function.
type WrapCountFilesCallHandle struct {
	*_imptest.CallableController[WrapCountFilesReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapCountFilesCallHandleEventually
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapCountFilesCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapCountFilesCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (h *WrapCountFilesCallHandle) ExpectReturnsEqual(v0 int, v1 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		if !_reflect.DeepEqual(h.Returned.Result1, v1) {
			h.T.Fatalf("expected return value 1 to be %v, got %v", v1, h.Returned.Result1)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapCountFilesCallHandle) ExpectReturnsMatch(v0 any, v1 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		ok, msg = _imptest.MatchValue(h.Returned.Result1, v1)
		if !ok {
			h.T.Fatalf("return value 1: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapCountFilesCallHandleEventually wraps a call handle for async expectation registration.
type WrapCountFilesCallHandleEventually struct {
	h *WrapCountFilesCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapCountFilesCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapCountFilesCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapCountFilesCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapCountFilesReturnsReturn holds the return values from the wrapped function.
type WrapCountFilesReturnsReturn struct {
	Result0 int
	Result1 error
}

// WrapCountFilesWrapperHandle is the test handle for a wrapped function.
type WrapCountFilesWrapperHandle struct {
	Method     *WrapCountFilesWrapperMethod
	Controller *_imptest.TargetController
}

// WrapCountFilesWrapperMethod wraps a function for testing.
type WrapCountFilesWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(visitor.TreeWalker, string) (int, error)
}

// Start executes the wrapped function in a goroutine.
func (m *WrapCountFilesWrapperMethod) Start(walker visitor.TreeWalker, root string) *WrapCountFilesCallHandle {
	handle := &WrapCountFilesCallHandle{
		CallableController: _imptest.NewCallableController[WrapCountFilesReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapCountFilesCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0, ret1 := m.callable(walker, root)
		handle.ReturnChan <- WrapCountFilesReturnsReturn{Result0: ret0, Result1: ret1}
	}()
	return handle
}

// WrapCountFiles wraps a function for testing.
func WrapCountFiles(t _imptest.TestReporter, fn func(visitor.TreeWalker, string) (int, error)) *WrapCountFilesWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapCountFilesWrapperHandle{
		Method: &WrapCountFilesWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
