// Code generated by impgen. DO NOT EDIT.

package visitor_test

import (
	visitor "github.com/toejough/imptest/UAT/variations/behavior/callbacks"
	_imptest "github.com/toejough/imptest/imptest"
	fs "io/fs"
)

// TreeWalkerMockHandle is the test handle for TreeWalker.
type TreeWalkerMockHandle struct {
	Mock       visitor.TreeWalker
	Method     *TreeWalkerMockMethods
	Controller *_imptest.Imp
}

// TreeWalkerMockMethods holds method wrappers for setting expectations.
type TreeWalkerMockMethods struct {
	Walk              *TreeWalkerMockWalkMethod
	WalkWithNamedType *TreeWalkerMockWalkWithNamedTypeMethod
}

// TreeWalkerMockWalkArgs holds typed arguments for Walk.
type TreeWalkerMockWalkArgs struct {
	Root string
	Fn   func(string, fs.DirEntry, error) error
}

// TreeWalkerMockWalkCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TreeWalkerMockWalkCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TreeWalkerMockWalkCall) GetArgs() TreeWalkerMockWalkArgs {
	raw := c.RawArgs()
	return TreeWalkerMockWalkArgs{
		Root: raw[0].(string),
		Fn:   raw[1].(func(string, fs.DirEntry, error) error),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TreeWalkerMockWalkCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// TreeWalkerMockWalkMethod wraps DependencyMethod with typed returns.
type TreeWalkerMockWalkMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *TreeWalkerMockWalkMethod) Eventually() *TreeWalkerMockWalkMethod {
	return &TreeWalkerMockWalkMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *TreeWalkerMockWalkMethod) ExpectCalledWithExactly(root string, fn func(string, fs.DirEntry, error) error) *TreeWalkerMockWalkCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(root, fn)
	return &TreeWalkerMockWalkCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *TreeWalkerMockWalkMethod) ExpectCalledWithMatches(matchers ...any) *TreeWalkerMockWalkCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &TreeWalkerMockWalkCall{DependencyCall: call}
}

// TreeWalkerMockWalkWithNamedTypeArgs holds typed arguments for WalkWithNamedType.
type TreeWalkerMockWalkWithNamedTypeArgs struct {
	Root string
	Fn   visitor.WalkFunc
}

// TreeWalkerMockWalkWithNamedTypeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TreeWalkerMockWalkWithNamedTypeCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TreeWalkerMockWalkWithNamedTypeCall) GetArgs() TreeWalkerMockWalkWithNamedTypeArgs {
	raw := c.RawArgs()
	return TreeWalkerMockWalkWithNamedTypeArgs{
		Root: raw[0].(string),
		Fn:   raw[1].(visitor.WalkFunc),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TreeWalkerMockWalkWithNamedTypeCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// TreeWalkerMockWalkWithNamedTypeMethod wraps DependencyMethod with typed returns.
type TreeWalkerMockWalkWithNamedTypeMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *TreeWalkerMockWalkWithNamedTypeMethod) Eventually() *TreeWalkerMockWalkWithNamedTypeMethod {
	return &TreeWalkerMockWalkWithNamedTypeMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *TreeWalkerMockWalkWithNamedTypeMethod) ExpectCalledWithExactly(root string, fn visitor.WalkFunc) *TreeWalkerMockWalkWithNamedTypeCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(root, fn)
	return &TreeWalkerMockWalkWithNamedTypeCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *TreeWalkerMockWalkWithNamedTypeMethod) ExpectCalledWithMatches(matchers ...any) *TreeWalkerMockWalkWithNamedTypeCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &TreeWalkerMockWalkWithNamedTypeCall{DependencyCall: call}
}

// MockTreeWalker creates a new TreeWalkerMockHandle for testing.
func MockTreeWalker(t _imptest.TestReporter) *TreeWalkerMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &TreeWalkerMockMethods{
		Walk:              &TreeWalkerMockWalkMethod{DependencyMethod: _imptest.NewDependencyMethod(ctrl, "Walk")},
		WalkWithNamedType: &TreeWalkerMockWalkWithNamedTypeMethod{DependencyMethod: _imptest.NewDependencyMethod(ctrl, "WalkWithNamedType")},
	}
	h := &TreeWalkerMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockTreeWalkerImpl{handle: h}
	return h
}

// mockTreeWalkerImpl implements visitor.TreeWalker.
type mockTreeWalkerImpl struct {
	handle *TreeWalkerMockHandle
}

// Walk implements visitor.TreeWalker.Walk.
func (impl *mockTreeWalkerImpl) Walk(root string, fn func(string, fs.DirEntry, error) error) error {
	call := &_imptest.GenericCall{
		MethodName:   "Walk",
		Args:         []any{root, fn},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// WalkWithNamedType implements visitor.TreeWalker.WalkWithNamedType.
func (impl *mockTreeWalkerImpl) WalkWithNamedType(root string, fn visitor.WalkFunc) error {
	call := &_imptest.GenericCall{
		MethodName:   "WalkWithNamedType",
		Args:         []any{root, fn},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
