// Code generated by impgen. DO NOT EDIT.

package whitebox

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// OpsMock is the mock for Ops.
type OpsMock struct {
	imp            *_imptest.Imp
	internalMethod *OpsMockinternalMethodMethod
	PublicMethod   *OpsMockPublicMethodMethod
}

// Interface returns the Ops implementation that can be passed to code under test.
func (m *OpsMock) Interface() Ops {
	return &mockOpsImpl{mock: m}
}

// OpsMockPublicMethodArgs holds typed arguments for PublicMethod.
type OpsMockPublicMethodArgs struct {
	X int
}

// OpsMockPublicMethodCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type OpsMockPublicMethodCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *OpsMockPublicMethodCall) GetArgs() OpsMockPublicMethodArgs {
	raw := c.RawArgs()
	return OpsMockPublicMethodArgs{
		X: raw[0].(int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *OpsMockPublicMethodCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// OpsMockPublicMethodMethod wraps DependencyMethod with typed returns.
type OpsMockPublicMethodMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *OpsMockPublicMethodMethod) ExpectCalledWithExactly(x int) *OpsMockPublicMethodCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(x)
	return &OpsMockPublicMethodCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *OpsMockPublicMethodMethod) ExpectCalledWithMatches(matchers ...any) *OpsMockPublicMethodCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &OpsMockPublicMethodCall{DependencyCall: call}
}

// OpsMockinternalMethodArgs holds typed arguments for internalMethod.
type OpsMockinternalMethodArgs struct {
	X int
}

// OpsMockinternalMethodCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type OpsMockinternalMethodCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *OpsMockinternalMethodCall) GetArgs() OpsMockinternalMethodArgs {
	raw := c.RawArgs()
	return OpsMockinternalMethodArgs{
		X: raw[0].(int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *OpsMockinternalMethodCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// OpsMockinternalMethodMethod wraps DependencyMethod with typed returns.
type OpsMockinternalMethodMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *OpsMockinternalMethodMethod) ExpectCalledWithExactly(x int) *OpsMockinternalMethodCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(x)
	return &OpsMockinternalMethodCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *OpsMockinternalMethodMethod) ExpectCalledWithMatches(matchers ...any) *OpsMockinternalMethodCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &OpsMockinternalMethodCall{DependencyCall: call}
}

// MockOps creates a new OpsMock for testing.
func MockOps(t _imptest.TestReporter) *OpsMock {
	imp := _imptest.NewImp(t)
	return &OpsMock{
		imp:            imp,
		internalMethod: &OpsMockinternalMethodMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "internalMethod")},
		PublicMethod:   &OpsMockPublicMethodMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "PublicMethod")},
	}
}

// mockOpsImpl implements Ops.
type mockOpsImpl struct {
	mock *OpsMock
}

// PublicMethod implements Ops.PublicMethod.
func (impl *mockOpsImpl) PublicMethod(x int) int {
	call := &_imptest.GenericCall{
		MethodName:   "PublicMethod",
		Args:         []any{x},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// internalMethod implements Ops.internalMethod.
func (impl *mockOpsImpl) internalMethod(x int) int {
	call := &_imptest.GenericCall{
		MethodName:   "internalMethod",
		Args:         []any{x},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}
