// Code generated by impgen. DO NOT EDIT.

package callable_test

import (
	callable "github.com/toejough/imptest/UAT/02-callable-wrappers"
	_imptest "github.com/toejough/imptest/imptest"
)

// ExternalServiceMock is the mock for ExternalService.
type ExternalServiceMock struct {
	imp       *_imptest.Imp
	FetchData *ExternalServiceMockFetchDataMethod
	Process   *ExternalServiceMockProcessMethod
}

// Interface returns the ExternalService implementation that can be passed to code under test.
func (m *ExternalServiceMock) Interface() callable.ExternalService {
	return &mockExternalServiceImpl{mock: m}
}

// ExternalServiceMockFetchDataArgs holds typed arguments for FetchData.
type ExternalServiceMockFetchDataArgs struct {
	Id int
}

// ExternalServiceMockFetchDataCall wraps DependencyCall with typed GetArgs.
type ExternalServiceMockFetchDataCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ExternalServiceMockFetchDataCall) GetArgs() ExternalServiceMockFetchDataArgs {
	raw := c.RawArgs()
	return ExternalServiceMockFetchDataArgs{
		Id: raw[0].(int),
	}
}

// ExternalServiceMockFetchDataMethod wraps DependencyMethod with typed returns.
type ExternalServiceMockFetchDataMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ExternalServiceMockFetchDataMethod) ExpectCalledWithExactly(id int) *ExternalServiceMockFetchDataCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(id)
	return &ExternalServiceMockFetchDataCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ExternalServiceMockFetchDataMethod) ExpectCalledWithMatches(matchers ...any) *ExternalServiceMockFetchDataCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ExternalServiceMockFetchDataCall{DependencyCall: call}
}

// ExternalServiceMockProcessArgs holds typed arguments for Process.
type ExternalServiceMockProcessArgs struct {
	Data string
}

// ExternalServiceMockProcessCall wraps DependencyCall with typed GetArgs.
type ExternalServiceMockProcessCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ExternalServiceMockProcessCall) GetArgs() ExternalServiceMockProcessArgs {
	raw := c.RawArgs()
	return ExternalServiceMockProcessArgs{
		Data: raw[0].(string),
	}
}

// ExternalServiceMockProcessMethod wraps DependencyMethod with typed returns.
type ExternalServiceMockProcessMethod struct {
	*_imptest.DependencyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ExternalServiceMockProcessMethod) ExpectCalledWithExactly(data string) *ExternalServiceMockProcessCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(data)
	return &ExternalServiceMockProcessCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ExternalServiceMockProcessMethod) ExpectCalledWithMatches(matchers ...any) *ExternalServiceMockProcessCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ExternalServiceMockProcessCall{DependencyCall: call}
}

// MockExternalService creates a new ExternalServiceMock for testing.
func MockExternalService(t _imptest.TestReporter) *ExternalServiceMock {
	imp := _imptest.NewImp(t)
	return &ExternalServiceMock{
		imp:       imp,
		FetchData: &ExternalServiceMockFetchDataMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "FetchData")},
		Process:   &ExternalServiceMockProcessMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Process")},
	}
}

// mockExternalServiceImpl implements callable.ExternalService.
type mockExternalServiceImpl struct {
	mock *ExternalServiceMock
}

// FetchData implements callable.ExternalService.FetchData.
func (impl *mockExternalServiceImpl) FetchData(id int) (string, error) {
	call := &_imptest.GenericCall{
		MethodName:   "FetchData",
		Args:         []any{id},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Process implements callable.ExternalService.Process.
func (impl *mockExternalServiceImpl) Process(data string) string {
	call := &_imptest.GenericCall{
		MethodName:   "Process",
		Args:         []any{data},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}
