// Code generated by impgen. DO NOT EDIT.

package callable_test

import (
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapCalculatorDivideReturnsReturn holds the return values from the wrapped function.
type WrapCalculatorDivideReturnsReturn struct {
	Result0 int
	Result1 bool
}

// WrapCalculatorDivideWrapper wraps a function for testing.
type WrapCalculatorDivideWrapper struct {
	*_imptest.CallableController[WrapCalculatorDivideReturnsReturn]
	callable func(int, int) (int, bool)
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (w *WrapCalculatorDivideWrapper) ExpectPanicEquals(expected any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, expected)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (w *WrapCalculatorDivideWrapper) ExpectPanicMatches(matcher any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, matcher)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (w *WrapCalculatorDivideWrapper) ExpectReturnsEqual(v0 int, v1 bool) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		if !_reflect.DeepEqual(w.Returned.Result0, v0) {
			w.T.Fatalf("expected return value 0 to be %v, got %v", v0, w.Returned.Result0)
		}
		if !_reflect.DeepEqual(w.Returned.Result1, v1) {
			w.T.Fatalf("expected return value 1 to be %v, got %v", v1, w.Returned.Result1)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (w *WrapCalculatorDivideWrapper) ExpectReturnsMatch(v0 any, v1 any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(w.Returned.Result0, v0)
		if !ok {
			w.T.Fatalf("return value 0: %s", msg)
		}
		ok, msg = _imptest.MatchValue(w.Returned.Result1, v1)
		if !ok {
			w.T.Fatalf("return value 1: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// Start executes the wrapped function in a goroutine.
func (w *WrapCalculatorDivideWrapper) Start(numerator int, denominator int) *WrapCalculatorDivideWrapper {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				w.PanicChan <- r
			}
		}()
		ret0, ret1 := w.callable(numerator, denominator)
		w.ReturnChan <- WrapCalculatorDivideReturnsReturn{Result0: ret0, Result1: ret1}
	}()
	return w
}

// WrapCalculatorDivide wraps a function for testing.
func WrapCalculatorDivide(t _imptest.TestReporter, fn func(int, int) (int, bool)) *WrapCalculatorDivideWrapper {
	return &WrapCalculatorDivideWrapper{
		CallableController: _imptest.NewCallableController[WrapCalculatorDivideReturnsReturn](t),
		callable:           fn,
	}
}
