// Code generated by impgen. DO NOT EDIT.

package callable_test

import (
	callable "github.com/toejough/imptest/UAT/02-callable-wrappers"
	_imptest "github.com/toejough/imptest/imptest"
	_testing "testing"
)

// CalculatorMultiply wraps a callable function for testing.
// Create with NewCalculatorMultiply(t, yourFunction), call Start() to execute,
// then use ExpectReturnedValuesAre/Should() or ExpectPanicWith() to verify behavior.
type CalculatorMultiply struct {
	*_imptest.CallableController[CalculatorMultiplyReturn]
	callable func(value int) int
}

// NewCalculatorMultiply creates a new wrapper for testing the callable function.
// Pass the function to test and a testing.TB to enable assertion failures.
//
// Example:
//
//	wrapper := NewCalculatorMultiply(t, myFunction)
//	wrapper.Start(args...).ExpectReturnedValuesAre(expectedVals...)
func NewCalculatorMultiply(t _testing.TB, callable func(value int) int) *CalculatorMultiply {
	return &CalculatorMultiply{
		CallableController: _imptest.NewCallableController[CalculatorMultiplyReturn](t),
		callable:           callable,
	}
}

// ExpectPanicWith asserts the callable panicked with a value matching the expectation.
// Use imptest.Any() to match any panic value, or imptest.Satisfies(fn) for custom matching.
// Fails the test if the callable returned normally or panicked with a different value.
func (s *CalculatorMultiply) ExpectPanicWith(expected any) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Panicked != nil {
		ok, msg := _imptest.MatchValue(s.Panicked, expected)
		if !ok {
			s.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	s.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnedValuesAre asserts the callable returned with exactly the specified values.
// Fails the test if the values don't match exactly or if the callable panicked.
// Uses == for comparison, so reference types must be the same instance.
func (s *CalculatorMultiply) ExpectReturnedValuesAre(v1 int) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Returned != nil {
		if s.Returned.Result0 != v1 {
			s.T.Fatalf("expected return value 0 to be %v, got %v", v1, s.Returned.Result0)
		}
		return
	}

	s.T.Fatalf("expected function to return, but it panicked with: %v", s.Panicked)
}

// ExpectReturnedValuesShould asserts return values match the given matchers.
// Use imptest.Any() to match any value, or imptest.Satisfies(fn) for custom matching.
// Fails the test if any matcher fails or if the callable panicked.
func (s *CalculatorMultiply) ExpectReturnedValuesShould(v1 any) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(s.Returned.Result0, v1)
		if !ok {
			s.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	s.T.Fatalf("expected function to return, but it panicked with: %v", s.Panicked)
}

// Start begins execution of the callable in a goroutine with the provided arguments.
// Returns the wrapper for method chaining with expectation methods.
// Captures both normal returns and panics for verification.
//
// Example:
//
//	wrapper.Start(arg1, arg2).ExpectReturnedValuesAre(expectedResult)
func (s *CalculatorMultiply) Start(value int) *CalculatorMultiply {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				s.PanicChan <- r
			}
		}()

		ret0 := s.callable(value)
		s.ReturnChan <- CalculatorMultiplyReturn{
			Result0: ret0,
		}
	}()
	return s
}

// CalculatorMultiplyResponse represents the response from the callable (either return or panic).
// Check EventType to determine if the callable returned normally or panicked.
// Access ReturnVal for return values or PanicVal for panic information.
type CalculatorMultiplyResponse struct {
	EventType string // "return" or "panic"
	ReturnVal *CalculatorMultiplyReturn
	PanicVal  any
}

// Type returns the event type: "return" for normal returns, "panic" for panics.
func (r *CalculatorMultiplyResponse) Type() string {
	return r.EventType
}

// CalculatorMultiplyReturn holds the return values from the callable function.
// Access individual return values via Result0, Result1, etc. fields.
type CalculatorMultiplyReturn struct {
	Result0 int
}
