// Code generated by impgen. DO NOT EDIT.
// impgen:hash:33443a9b10022fc5

package matching_test

import (
	_imptest "github.com/toejough/imptest"
	matching "github.com/toejough/imptest/UAT/variations/behavior/matching"
)

// ComplexServiceImp holds method wrappers for setting expectations on ComplexService.
type ComplexServiceImp struct {
	Process *ComplexServiceMockProcessMethod
	// Eventually provides async versions of all methods for concurrent code.
	Eventually *ComplexServiceImpEventually
}

// ComplexServiceImpEventually holds async method wrappers for ComplexService.
type ComplexServiceImpEventually struct {
	Process *ComplexServiceMockProcessMethod
}

// ComplexServiceMockProcessArgs holds typed arguments for Process.
type ComplexServiceMockProcessArgs struct {
	D matching.Data
}

// ComplexServiceMockProcessCall wraps DependencyCall with typed GetArgs and Return.
type ComplexServiceMockProcessCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ComplexServiceMockProcessCall) GetArgs() ComplexServiceMockProcessArgs {
	raw := c.RawArgs()
	return ComplexServiceMockProcessArgs{
		D: raw[0].(matching.Data),
	}
}

// Return specifies the typed values the mock should return.
func (c *ComplexServiceMockProcessCall) Return(result0 bool) {
	c.DependencyCall.Return(result0)
}

// ComplexServiceMockProcessMethod wraps DependencyMethod with typed returns.
type ComplexServiceMockProcessMethod struct {
	*_imptest.DependencyMethod
}

// ArgsEqual waits for a call with exactly the specified arguments.
func (m *ComplexServiceMockProcessMethod) ArgsEqual(d matching.Data) *ComplexServiceMockProcessCall {
	call := m.DependencyMethod.ArgsEqual(d)
	return &ComplexServiceMockProcessCall{DependencyCall: call}
}

// ArgsShould waits for a call with arguments matching the given matchers.
func (m *ComplexServiceMockProcessMethod) ArgsShould(matchers ...any) *ComplexServiceMockProcessCall {
	call := m.DependencyMethod.ArgsShould(matchers...)
	return &ComplexServiceMockProcessCall{DependencyCall: call}
}

// MockComplexService creates a mock ComplexService and returns (mock, expectation handle).
func MockComplexService(t _imptest.TestReporter) (matching.ComplexService, *ComplexServiceImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &ComplexServiceImp{
		Process: newComplexServiceMockProcessMethod(_imptest.NewDependencyMethod(ctrl, "Process")),
	}
	imp.Eventually = &ComplexServiceImpEventually{
		Process: newComplexServiceMockProcessMethod(_imptest.NewDependencyMethod(ctrl, "Process").AsEventually()),
	}
	mock := &mockComplexServiceImpl{ctrl: ctrl}
	return mock, imp
}

// mockComplexServiceImpl implements matching.ComplexService.
type mockComplexServiceImpl struct {
	ctrl *_imptest.Imp
}

// Process implements matching.ComplexService.Process.
func (impl *mockComplexServiceImpl) Process(d matching.Data) bool {
	call := &_imptest.GenericCall{
		MethodName:   "Process",
		Args:         []any{d},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 bool
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(bool); ok {
			result1 = value
		}
	}

	return result1
}

// newComplexServiceMockProcessMethod creates a typed method wrapper.
func newComplexServiceMockProcessMethod(dm *_imptest.DependencyMethod) *ComplexServiceMockProcessMethod {
	return &ComplexServiceMockProcessMethod{DependencyMethod: dm}
}
