// Code generated by impgen. DO NOT EDIT.
// impgen:hash:a9d223c8b7290daa

package core_test

import (
	_imptest "github.com/toejough/imptest"
	core "github.com/toejough/imptest/internal/core"
)

// TestReporterMockFatalfArgs holds typed arguments for Fatalf.
type TestReporterMockFatalfArgs struct {
	Format string
	Args   []any
}

// TestReporterMockFatalfCall wraps DependencyCall with typed GetArgs.
type TestReporterMockFatalfCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TestReporterMockFatalfCall) GetArgs() TestReporterMockFatalfArgs {
	raw := c.RawArgs()
	return TestReporterMockFatalfArgs{
		Format: raw[0].(string),
		Args:   raw[1].([]any),
	}
}

// TestReporterMockFatalfMethod wraps DependencyMethod with typed returns.
type TestReporterMockFatalfMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *TestReporterMockFatalfMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *TestReporterMockFatalfMethod) ExpectCalledWithExactly(format string, args ...any) *TestReporterMockFatalfCall {
	callArgs := []any{format}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.ExpectCalledWithExactly(callArgs...)
	return &TestReporterMockFatalfCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *TestReporterMockFatalfMethod) ExpectCalledWithMatches(matchers ...any) *TestReporterMockFatalfCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &TestReporterMockFatalfCall{DependencyCall: call}
}

// TestReporterMockHandle is the test handle for TestReporter.
type TestReporterMockHandle struct {
	Mock       core.TestReporter
	Method     *TestReporterMockMethods
	Controller *_imptest.Imp
}

// TestReporterMockMethods holds method wrappers for setting expectations.
type TestReporterMockMethods struct {
	Helper *_imptest.DependencyMethod
	Fatalf *TestReporterMockFatalfMethod
}

// MockTestReporter creates a new TestReporterMockHandle for testing.
func MockTestReporter(t _imptest.TestReporter) *TestReporterMockHandle {
	ctrl := _imptest.GetOrCreateImp(t)
	methods := &TestReporterMockMethods{
		Helper: _imptest.NewDependencyMethod(ctrl, "Helper"),
		Fatalf: newTestReporterMockFatalfMethod(_imptest.NewDependencyMethod(ctrl, "Fatalf")),
	}
	h := &TestReporterMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockTestReporterImpl{handle: h}
	return h
}

// mockTestReporterImpl implements core.TestReporter.
type mockTestReporterImpl struct {
	handle *TestReporterMockHandle
}

// Fatalf implements core.TestReporter.Fatalf.
func (impl *mockTestReporterImpl) Fatalf(format string, args ...any) {
	callArgs := []any{format}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Fatalf",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Helper implements core.TestReporter.Helper.
func (impl *mockTestReporterImpl) Helper() {
	call := &_imptest.GenericCall{
		MethodName:   "Helper",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// newTestReporterMockFatalfMethod creates a typed method wrapper with Eventually initialized.
func newTestReporterMockFatalfMethod(dm *_imptest.DependencyMethod) *TestReporterMockFatalfMethod {
	m := &TestReporterMockFatalfMethod{DependencyMethod: dm}
	m.Eventually = &TestReporterMockFatalfMethod{DependencyMethod: dm.Eventually}
	return m
}
