// Code generated by impgen. DO NOT EDIT.
// impgen:hash:a9d223c8b7290daa

package core_test

import (
	_imptest "github.com/toejough/imptest"
	core "github.com/toejough/imptest/internal/core"
)

// TestReporterImp holds method wrappers for setting expectations on TestReporter.
type TestReporterImp struct {
	Helper *_imptest.DependencyMethod
	Fatalf *TestReporterMockFatalfMethod
}

// TestReporterMockFatalfArgs holds typed arguments for Fatalf.
type TestReporterMockFatalfArgs struct {
	Format string
	Args   []any
}

// TestReporterMockFatalfCall wraps DependencyCall with typed GetArgs.
type TestReporterMockFatalfCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TestReporterMockFatalfCall) GetArgs() TestReporterMockFatalfArgs {
	raw := c.RawArgs()
	return TestReporterMockFatalfArgs{
		Format: raw[0].(string),
		Args:   raw[1].([]any),
	}
}

// TestReporterMockFatalfMethod wraps DependencyMethod with typed returns.
type TestReporterMockFatalfMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *TestReporterMockFatalfMethod
}

// Expect waits for a call with exactly the specified arguments.
func (m *TestReporterMockFatalfMethod) Expect(format string, args ...any) *TestReporterMockFatalfCall {
	callArgs := []any{format}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := m.DependencyMethod.Expect(callArgs...)
	return &TestReporterMockFatalfCall{DependencyCall: call}
}

// Match waits for a call with arguments matching the given matchers.
func (m *TestReporterMockFatalfMethod) Match(matchers ...any) *TestReporterMockFatalfCall {
	call := m.DependencyMethod.Match(matchers...)
	return &TestReporterMockFatalfCall{DependencyCall: call}
}

// MockTestReporter creates a mock TestReporter and returns (mock, expectation handle).
func MockTestReporter(t _imptest.TestReporter) (core.TestReporter, *TestReporterImp) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := &TestReporterImp{
		Helper: _imptest.NewDependencyMethod(ctrl, "Helper"),
		Fatalf: newTestReporterMockFatalfMethod(_imptest.NewDependencyMethod(ctrl, "Fatalf")),
	}
	mock := &mockTestReporterImpl{ctrl: ctrl}
	return mock, imp
}

// mockTestReporterImpl implements core.TestReporter.
type mockTestReporterImpl struct {
	ctrl *_imptest.Imp
}

// Fatalf implements core.TestReporter.Fatalf.
func (impl *mockTestReporterImpl) Fatalf(format string, args ...any) {
	callArgs := []any{format}
	for _, v := range args {
		callArgs = append(callArgs, v)
	}
	call := &_imptest.GenericCall{
		MethodName:   "Fatalf",
		Args:         callArgs,
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Helper implements core.TestReporter.Helper.
func (impl *mockTestReporterImpl) Helper() {
	call := &_imptest.GenericCall{
		MethodName:   "Helper",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.ctrl.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// newTestReporterMockFatalfMethod creates a typed method wrapper with Eventually initialized.
func newTestReporterMockFatalfMethod(dm *_imptest.DependencyMethod) *TestReporterMockFatalfMethod {
	m := &TestReporterMockFatalfMethod{DependencyMethod: dm}
	m.Eventually = &TestReporterMockFatalfMethod{DependencyMethod: dm.Eventually}
	return m
}
