// Code generated by impgen. DO NOT EDIT.
// impgen:hash:4c443206e0a52f79

package structlit_test

import (
	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

// WrapGetDefaultsCallHandle represents a single call to the wrapped function.
type WrapGetDefaultsCallHandle struct {
	*_imptest.CallableController[WrapGetDefaultsReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapGetDefaultsCallHandleEventually
}

// ExpectPanic verifies the function panics with the expected value.
func (h *WrapGetDefaultsCallHandle) ExpectPanic(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatch verifies the function panics with a value matching the given matcher.
func (h *WrapGetDefaultsCallHandle) ExpectPanicMatch(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturn verifies the function returned the expected values.
func (h *WrapGetDefaultsCallHandle) ExpectReturn(v0 struct {
	MaxRetries int
	Timeout    int
}) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnMatch verifies the return values match the given matchers.
func (h *WrapGetDefaultsCallHandle) ExpectReturnMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapGetDefaultsCallHandleEventually wraps a call handle for async expectation registration.
type WrapGetDefaultsCallHandleEventually struct {
	h *WrapGetDefaultsCallHandle
}

// ExpectPanic registers an async expectation for a panic value.
func (e *WrapGetDefaultsCallHandleEventually) ExpectPanic(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ExpectReturn registers an async expectation for return values.
func (e *WrapGetDefaultsCallHandleEventually) ExpectReturn(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *WrapGetDefaultsCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapGetDefaultsReturnsReturn holds the return values from the wrapped function.
type WrapGetDefaultsReturnsReturn struct {
	Result0 struct {
		MaxRetries int
		Timeout    int
	}
}

// WrapGetDefaultsWrapperHandle is the test handle for a wrapped function.
type WrapGetDefaultsWrapperHandle struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func() struct {
		MaxRetries int
		Timeout    int
	}
}

// Start executes the wrapped function in a goroutine.
func (w *WrapGetDefaultsWrapperHandle) Start() *WrapGetDefaultsCallHandle {
	handle := &WrapGetDefaultsCallHandle{
		CallableController: _imptest.NewCallableController[WrapGetDefaultsReturnsReturn](w.t),
		controller:         w.controller,
	}
	handle.Eventually = &WrapGetDefaultsCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := w.callable()
		handle.ReturnChan <- WrapGetDefaultsReturnsReturn{Result0: ret0}
	}()
	return handle
}

// WrapGetDefaults wraps a function for testing.
func WrapGetDefaults(t _imptest.TestReporter, fn func() struct {
	MaxRetries int
	Timeout    int
}) *WrapGetDefaultsWrapperHandle {
	return &WrapGetDefaultsWrapperHandle{
		t:          t,
		controller: _imptest.NewTargetController(t),
		callable:   fn,
	}
}
