// Code generated by impgen. DO NOT EDIT.

package callable_test

import (
	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

// WrapCalculatorProcessValueCallHandle represents a single call to the wrapped function.
type WrapCalculatorProcessValueCallHandle struct {
	*_imptest.CallableController[WrapCalculatorProcessValueReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapCalculatorProcessValueCallHandleEventually
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapCalculatorProcessValueCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapCalculatorProcessValueCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (h *WrapCalculatorProcessValueCallHandle) ExpectReturnsEqual(v0 int) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapCalculatorProcessValueCallHandle) ExpectReturnsMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapCalculatorProcessValueCallHandleEventually wraps a call handle for async expectation registration.
type WrapCalculatorProcessValueCallHandleEventually struct {
	h *WrapCalculatorProcessValueCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapCalculatorProcessValueCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapCalculatorProcessValueCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapCalculatorProcessValueCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapCalculatorProcessValueReturnsReturn holds the return values from the wrapped function.
type WrapCalculatorProcessValueReturnsReturn struct {
	Result0 int
}

// WrapCalculatorProcessValueWrapperHandle is the test handle for a wrapped function.
type WrapCalculatorProcessValueWrapperHandle struct {
	Method     *WrapCalculatorProcessValueWrapperMethod
	Controller *_imptest.TargetController
}

// WrapCalculatorProcessValueWrapperMethod wraps a function for testing.
type WrapCalculatorProcessValueWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(int) int
}

// Start executes the wrapped function in a goroutine.
func (m *WrapCalculatorProcessValueWrapperMethod) Start(value int) *WrapCalculatorProcessValueCallHandle {
	handle := &WrapCalculatorProcessValueCallHandle{
		CallableController: _imptest.NewCallableController[WrapCalculatorProcessValueReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapCalculatorProcessValueCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := m.callable(value)
		handle.ReturnChan <- WrapCalculatorProcessValueReturnsReturn{Result0: ret0}
	}()
	return handle
}

// WrapCalculatorProcessValue wraps a function for testing.
func WrapCalculatorProcessValue(t _imptest.TestReporter, fn func(int) int) *WrapCalculatorProcessValueWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapCalculatorProcessValueWrapperHandle{
		Method: &WrapCalculatorProcessValueWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
