// Code generated by impgen. DO NOT EDIT.
// impgen:hash:cb327c56de65eae3

package callable_test

import (
	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

// StartCalculatorAddCallHandle represents a single call to the wrapped function.
type StartCalculatorAddCallHandle struct {
	*_imptest.CallableController[StartCalculatorAddReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *StartCalculatorAddCallHandleEventually
}

// ExpectPanic verifies the function panics with the expected value.
func (h *StartCalculatorAddCallHandle) ExpectPanic(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatch verifies the function panics with a value matching the given matcher.
func (h *StartCalculatorAddCallHandle) ExpectPanicMatch(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturn verifies the function returned the expected values.
func (h *StartCalculatorAddCallHandle) ExpectReturn(v0 int) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnMatch verifies the return values match the given matchers.
func (h *StartCalculatorAddCallHandle) ExpectReturnMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// StartCalculatorAddCallHandleEventually wraps a call handle for async expectation registration.
type StartCalculatorAddCallHandleEventually struct {
	h *StartCalculatorAddCallHandle
}

// ExpectPanic registers an async expectation for a panic value.
func (e *StartCalculatorAddCallHandleEventually) ExpectPanic(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ExpectReturn registers an async expectation for return values.
func (e *StartCalculatorAddCallHandleEventually) ExpectReturn(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *StartCalculatorAddCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// StartCalculatorAddReturnsReturn holds the return values from the wrapped function.
type StartCalculatorAddReturnsReturn struct {
	Result0 int
}

// StartCalculatorAdd starts the wrapped function in a goroutine for testing.
func StartCalculatorAdd(t _imptest.TestReporter, fn func(int, int) int, a int, b int) *StartCalculatorAddCallHandle {
	handle := &StartCalculatorAddCallHandle{
		CallableController: _imptest.NewCallableController[StartCalculatorAddReturnsReturn](t),
		controller:         _imptest.NewTargetController(t),
	}
	handle.Eventually = &StartCalculatorAddCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := fn(a, b)
		handle.ReturnChan <- StartCalculatorAddReturnsReturn{Result0: ret0}
	}()
	return handle
}
