// Code generated by impgen. DO NOT EDIT.
// impgen:hash:4e35f003e0202588

package callable_test

import (
	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

// StartPanicIntFuncCallHandle represents a single call to the wrapped function.
type StartPanicIntFuncCallHandle struct {
	*_imptest.CallableController[StartPanicIntFuncReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *StartPanicIntFuncCallHandleEventually
}

// ExpectPanic verifies the function panics with the expected value.
func (h *StartPanicIntFuncCallHandle) ExpectPanic(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatch verifies the function panics with a value matching the given matcher.
func (h *StartPanicIntFuncCallHandle) ExpectPanicMatch(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturn verifies the function returned the expected values.
func (h *StartPanicIntFuncCallHandle) ExpectReturn(v0 int) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnMatch verifies the return values match the given matchers.
func (h *StartPanicIntFuncCallHandle) ExpectReturnMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// StartPanicIntFuncCallHandleEventually wraps a call handle for async expectation registration.
type StartPanicIntFuncCallHandleEventually struct {
	h *StartPanicIntFuncCallHandle
}

// ExpectPanic registers an async expectation for a panic value.
func (e *StartPanicIntFuncCallHandleEventually) ExpectPanic(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ExpectReturn registers an async expectation for return values.
func (e *StartPanicIntFuncCallHandleEventually) ExpectReturn(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *StartPanicIntFuncCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// StartPanicIntFuncReturnsReturn holds the return values from the wrapped function.
type StartPanicIntFuncReturnsReturn struct {
	Result0 int
}

// StartPanicIntFunc starts the wrapped function in a goroutine for testing.
func StartPanicIntFunc(t _imptest.TestReporter, fn func() int) *StartPanicIntFuncCallHandle {
	handle := &StartPanicIntFuncCallHandle{
		CallableController: _imptest.NewCallableController[StartPanicIntFuncReturnsReturn](t),
		controller:         _imptest.NewTargetController(t),
	}
	handle.Eventually = &StartPanicIntFuncCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := fn()
		handle.ReturnChan <- StartPanicIntFuncReturnsReturn{Result0: ret0}
	}()
	return handle
}
