// Code generated by impgen. DO NOT EDIT.

package callable_test

import (
	callable "github.com/toejough/imptest/UAT/core/wrapper-function"
	_imptest "github.com/toejough/imptest/imptest"
)

// ExternalServiceMockFetchDataArgs holds typed arguments for FetchData.
type ExternalServiceMockFetchDataArgs struct {
	Id int
}

// ExternalServiceMockFetchDataCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ExternalServiceMockFetchDataCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ExternalServiceMockFetchDataCall) GetArgs() ExternalServiceMockFetchDataArgs {
	raw := c.RawArgs()
	return ExternalServiceMockFetchDataArgs{
		Id: raw[0].(int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ExternalServiceMockFetchDataCall) InjectReturnValues(result0 string, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// ExternalServiceMockFetchDataMethod wraps DependencyMethod with typed returns.
type ExternalServiceMockFetchDataMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *ExternalServiceMockFetchDataMethod) Eventually() *ExternalServiceMockFetchDataMethod {
	return &ExternalServiceMockFetchDataMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ExternalServiceMockFetchDataMethod) ExpectCalledWithExactly(id int) *ExternalServiceMockFetchDataCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(id)
	return &ExternalServiceMockFetchDataCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ExternalServiceMockFetchDataMethod) ExpectCalledWithMatches(matchers ...any) *ExternalServiceMockFetchDataCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ExternalServiceMockFetchDataCall{DependencyCall: call}
}

// ExternalServiceMockHandle is the test handle for ExternalService.
type ExternalServiceMockHandle struct {
	Mock       callable.ExternalService
	Method     *ExternalServiceMockMethods
	Controller *_imptest.Imp
}

// ExternalServiceMockMethods holds method wrappers for setting expectations.
type ExternalServiceMockMethods struct {
	FetchData *ExternalServiceMockFetchDataMethod
	Process   *ExternalServiceMockProcessMethod
}

// ExternalServiceMockProcessArgs holds typed arguments for Process.
type ExternalServiceMockProcessArgs struct {
	Data string
}

// ExternalServiceMockProcessCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ExternalServiceMockProcessCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ExternalServiceMockProcessCall) GetArgs() ExternalServiceMockProcessArgs {
	raw := c.RawArgs()
	return ExternalServiceMockProcessArgs{
		Data: raw[0].(string),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ExternalServiceMockProcessCall) InjectReturnValues(result0 string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ExternalServiceMockProcessMethod wraps DependencyMethod with typed returns.
type ExternalServiceMockProcessMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *ExternalServiceMockProcessMethod) Eventually() *ExternalServiceMockProcessMethod {
	return &ExternalServiceMockProcessMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ExternalServiceMockProcessMethod) ExpectCalledWithExactly(data string) *ExternalServiceMockProcessCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(data)
	return &ExternalServiceMockProcessCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ExternalServiceMockProcessMethod) ExpectCalledWithMatches(matchers ...any) *ExternalServiceMockProcessCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ExternalServiceMockProcessCall{DependencyCall: call}
}

// MockExternalService creates a new ExternalServiceMockHandle for testing.
func MockExternalService(t _imptest.TestReporter) *ExternalServiceMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &ExternalServiceMockMethods{
		FetchData: &ExternalServiceMockFetchDataMethod{DependencyMethod: _imptest.NewDependencyMethod(ctrl, "FetchData")},
		Process:   &ExternalServiceMockProcessMethod{DependencyMethod: _imptest.NewDependencyMethod(ctrl, "Process")},
	}
	h := &ExternalServiceMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockExternalServiceImpl{handle: h}
	return h
}

// mockExternalServiceImpl implements callable.ExternalService.
type mockExternalServiceImpl struct {
	handle *ExternalServiceMockHandle
}

// FetchData implements callable.ExternalService.FetchData.
func (impl *mockExternalServiceImpl) FetchData(id int) (string, error) {
	call := &_imptest.GenericCall{
		MethodName:   "FetchData",
		Args:         []any{id},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Process implements callable.ExternalService.Process.
func (impl *mockExternalServiceImpl) Process(data string) string {
	call := &_imptest.GenericCall{
		MethodName:   "Process",
		Args:         []any{data},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}
