//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
)

func main() {
	fmt.Printf("Running %s go on %s\n", os.Args[0], os.Getenv("GOFILE"))

	cwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	fmt.Printf("  cwd = %s\n", cwd)
	fmt.Printf("  os.Args = %#v\n", os.Args)

	for _, ev := range []string{"GOARCH", "GOOS", "GOFILE", "GOLINE", "GOPACKAGE", "DOLLAR"} {
		fmt.Println("  ", ev, "=", os.Getenv(ev))
	}

	// Instead of just reading GOFILE, read all Go files in the package directory (GOPACKAGE)
	pkgName := os.Getenv("GOPACKAGE")
	if pkgName == "" {
		fmt.Println("  GOPACKAGE not set; cannot search package")
		return
	}

	// Find the directory containing the package
	pkgDir := cwd // assume current dir is the package dir
	entries, err := os.ReadDir(pkgDir)
	if err != nil {
		fmt.Printf("  error reading package dir %q: %v\n", pkgDir, err)
		return
	}

	var files []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if len(name) > 3 && name[len(name)-3:] == ".go" && name != "generated.go" {
			files = append(files, filepath.Join(pkgDir, name))
		}
	}

	fset := token.NewFileSet()
	var astFiles []*ast.File
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			fmt.Printf("  error reading file %q: %v\n", file, err)
			continue
		}
		f, err := parser.ParseFile(fset, file, data, parser.ParseComments)
		if err != nil {
			fmt.Printf("  error parsing file %q: %v\n", file, err)
			continue
		}
		astFiles = append(astFiles, f)
	}

	// Pretty print all interfaces in the package
	fmt.Printf("----- All interfaces in package %s -----\n", pkgName)
	for _, fileAst := range astFiles {
		ast.Inspect(fileAst, func(n ast.Node) bool {
			ts, ok := n.(*ast.TypeSpec)
			if ok {
				if iface, ok2 := ts.Type.(*ast.InterfaceType); ok2 {
					fmt.Printf("*ast.TypeSpec (Name: %q)\n", ts.Name.Name)
					printAstTree(iface, "  ")
					return false
				}
			}
			return true
		})
	}
	fmt.Printf("----- end interfaces in package %s -----\n", pkgName)

	// Search for the interface in all files
	var identifiedInterface *ast.InterfaceType
	if len(os.Args) > 0 {
		matchName := os.Args[len(os.Args)-1]
		for _, fileAst := range astFiles {
			ast.Inspect(fileAst, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if ok {
					if iface, ok2 := ts.Type.(*ast.InterfaceType); ok2 && ts.Name.Name == matchName {
						identifiedInterface = iface
						return false
					}
				}
				return true
			})
			if identifiedInterface != nil {
				break
			}
		}

		if identifiedInterface != nil {
			var buf bytes.Buffer
			buf.WriteString("package main\n\n")
			buf.WriteString("// Code generated by generate.go. DO NOT EDIT.\n\n")
			buf.WriteString("type interfaceImplementation struct{}\n\n")

			// Generate method stubs for each method in the interface
			for _, field := range identifiedInterface.Methods.List {
				// Only methods (not embedded interfaces)
				if len(field.Names) == 0 {
					continue
				}
				for _, name := range field.Names {
					// Build the function signature
					ftype, ok := field.Type.(*ast.FuncType)
					if !ok {
						continue
					}
					buf.WriteString("func (interfaceImplementation) ")
					buf.WriteString(name.Name)
					buf.WriteString(renderFieldList(fset, ftype.Params, true))
					buf.WriteString(renderFieldList(fset, ftype.Results, false))
					buf.WriteString(" { panic(\"not implemented\") }\n\n")
				}
			}

			// Format the code
			formatted, err := format.Source(buf.Bytes())
			if err != nil {
				fmt.Printf("error formatting generated code: %v\n", err)
				return
			}

			// Write to generated.go
			if err := os.WriteFile("generated.go", formatted, 0644); err != nil {
				fmt.Printf("error writing generated.go: %v\n", err)
				return
			}
			fmt.Println("generated.go written successfully.")
		} else {
			fmt.Printf("No interface named %q found in package.\n", matchName)
		}
	}
}

// printAstTree recursively prints the AST node tree with indentation
func printAstTree(node interface{}, indent string) {
	switch n := node.(type) {
	case nil:
		return
	case *ast.Ident:
		typeName := fmt.Sprintf("%T", n)
		fmt.Printf("%s%s (Name: %q)\n", indent, typeName, n.Name)
		return
	case ast.Node:
		typeName := fmt.Sprintf("%T", n)
		fmt.Printf("%s%s\n", indent, typeName)
		indent2 := indent + "  "
		ast.Inspect(n, func(child ast.Node) bool {
			if child != n && child != nil {
				printAstTree(child, indent2)
				return false
			}
			return true
		})
	}
}

// printTypeSpecsWithInterface prints TypeSpec nodes whose immediate child is an InterfaceType
func printTypeSpecsWithInterface(node ast.Node, indent string) {
	ast.Inspect(node, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if ok {
			if iface, ok2 := ts.Type.(*ast.InterfaceType); ok2 {
				fmt.Printf("%s*ast.TypeSpec (Name: %q)\n", indent, ts.Name.Name)
				printAstTree(iface, indent+"  ")
				return false // don't descend into children again
			}
		}
		return true
	})
}

// printTypeSpecsWithInterfaceName prints TypeSpec nodes whose immediate child is an InterfaceType and whose name matches
func printTypeSpecsWithInterfaceName(node ast.Node, indent, matchName string) {
	ast.Inspect(node, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if ok {
			if iface, ok2 := ts.Type.(*ast.InterfaceType); ok2 && ts.Name.Name == matchName {
				fmt.Printf("%s*ast.TypeSpec (Name: %q)\n", indent, ts.Name.Name)
				printAstTree(iface, indent+"  ")
				return false // don't descend into children again
			}
		}
		return true
	})
}

// renderFieldList renders a *ast.FieldList as Go code (params/results)
func renderFieldList(fset *token.FileSet, fl *ast.FieldList, isParams bool) string {
	if fl == nil || len(fl.List) == 0 {
		if isParams {
			return "()"
		}
		return ""
	}
	var buf bytes.Buffer
	buf.WriteString("(")
	for i, field := range fl.List {
		if i > 0 {
			buf.WriteString(", ")
		}
		// Names
		for j, name := range field.Names {
			if j > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(name.Name)
		}
		// Type
		if len(field.Names) > 0 {
			buf.WriteString(" ")
		}
		buf.WriteString(exprToString(fset, field.Type))
	}
	buf.WriteString(")")
	return buf.String()
}

// exprToString renders an ast.Expr to Go code
func exprToString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	printer.Fprint(&buf, fset, expr)
	return buf.String()
}
