// Code generated by impgen. DO NOT EDIT.

package concurrency_test

import (
	concurrency "github.com/toejough/imptest/UAT/06-concurrency"
	_imptest "github.com/toejough/imptest/imptest"
)

// SlowServiceMock is the mock for SlowService.
type SlowServiceMock struct {
	imp *_imptest.Imp
	DoA *SlowServiceMockDoAMethod
	DoB *SlowServiceMockDoBMethod
}

// Interface returns the SlowService implementation that can be passed to code under test.
func (m *SlowServiceMock) Interface() concurrency.SlowService {
	return &mockSlowServiceImpl{mock: m}
}

// SlowServiceMockDoAArgs holds typed arguments for DoA.
type SlowServiceMockDoAArgs struct {
	Id int
}

// SlowServiceMockDoACall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SlowServiceMockDoACall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SlowServiceMockDoACall) GetArgs() SlowServiceMockDoAArgs {
	raw := c.RawArgs()
	return SlowServiceMockDoAArgs{
		Id: raw[0].(int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SlowServiceMockDoACall) InjectReturnValues(result0 string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// SlowServiceMockDoAMethod wraps DependencyMethod with typed returns.
type SlowServiceMockDoAMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *SlowServiceMockDoAMethod) Eventually() *SlowServiceMockDoAMethod {
	return &SlowServiceMockDoAMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SlowServiceMockDoAMethod) ExpectCalledWithExactly(id int) *SlowServiceMockDoACall {
	call := m.DependencyMethod.ExpectCalledWithExactly(id)
	return &SlowServiceMockDoACall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SlowServiceMockDoAMethod) ExpectCalledWithMatches(matchers ...any) *SlowServiceMockDoACall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SlowServiceMockDoACall{DependencyCall: call}
}

// SlowServiceMockDoBArgs holds typed arguments for DoB.
type SlowServiceMockDoBArgs struct {
	Id int
}

// SlowServiceMockDoBCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SlowServiceMockDoBCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SlowServiceMockDoBCall) GetArgs() SlowServiceMockDoBArgs {
	raw := c.RawArgs()
	return SlowServiceMockDoBArgs{
		Id: raw[0].(int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SlowServiceMockDoBCall) InjectReturnValues(result0 string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// SlowServiceMockDoBMethod wraps DependencyMethod with typed returns.
type SlowServiceMockDoBMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *SlowServiceMockDoBMethod) Eventually() *SlowServiceMockDoBMethod {
	return &SlowServiceMockDoBMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SlowServiceMockDoBMethod) ExpectCalledWithExactly(id int) *SlowServiceMockDoBCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(id)
	return &SlowServiceMockDoBCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SlowServiceMockDoBMethod) ExpectCalledWithMatches(matchers ...any) *SlowServiceMockDoBCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SlowServiceMockDoBCall{DependencyCall: call}
}

// MockSlowService creates a new SlowServiceMock for testing.
func MockSlowService(t _imptest.TestReporter) *SlowServiceMock {
	imp := _imptest.NewImp(t)
	return &SlowServiceMock{
		imp: imp,
		DoA: &SlowServiceMockDoAMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "DoA")},
		DoB: &SlowServiceMockDoBMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "DoB")},
	}
}

// mockSlowServiceImpl implements concurrency.SlowService.
type mockSlowServiceImpl struct {
	mock *SlowServiceMock
}

// DoA implements concurrency.SlowService.DoA.
func (impl *mockSlowServiceImpl) DoA(id int) string {
	call := &_imptest.GenericCall{
		MethodName:   "DoA",
		Args:         []any{id},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}

// DoB implements concurrency.SlowService.DoB.
func (impl *mockSlowServiceImpl) DoB(id int) string {
	call := &_imptest.GenericCall{
		MethodName:   "DoB",
		Args:         []any{id},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}
