// Code generated by impgen. DO NOT EDIT.

package mockfunction_test

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// ValidateInputMockArgs holds typed arguments for ValidateInput.
type ValidateInputMockArgs struct {
	Input string
}

// ValidateInputMockCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ValidateInputMockCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ValidateInputMockCall) GetArgs() ValidateInputMockArgs {
	raw := c.RawArgs()
	return ValidateInputMockArgs{
		Input: raw[0].(string),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ValidateInputMockCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ValidateInputMockHandle is the test handle for ValidateInput function.
type ValidateInputMockHandle struct {
	Mock       func(input string) error
	Method     *ValidateInputMockMethod
	Controller *_imptest.Imp
}

// ValidateInputMockMethod wraps DependencyMethod with typed returns.
type ValidateInputMockMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *ValidateInputMockMethod) Eventually() *ValidateInputMockMethod {
	return &ValidateInputMockMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ValidateInputMockMethod) ExpectCalledWithExactly(input string) *ValidateInputMockCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(input)
	return &ValidateInputMockCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ValidateInputMockMethod) ExpectCalledWithMatches(matchers ...any) *ValidateInputMockCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ValidateInputMockCall{DependencyCall: call}
}

// MockValidateInput creates a new ValidateInputMockHandle for testing.
func MockValidateInput(t _imptest.TestReporter) *ValidateInputMockHandle {
	ctrl := _imptest.NewImp(t)
	h := &ValidateInputMockHandle{
		Controller: ctrl,
		Method:     &ValidateInputMockMethod{DependencyMethod: _imptest.NewDependencyMethod(ctrl, "ValidateInput")},
	}
	h.Mock = func(input string) error {
		call := &_imptest.GenericCall{
			MethodName:   "ValidateInput",
			Args:         []any{input},
			ResponseChan: make(chan _imptest.GenericResponse, 1),
		}
		h.Controller.CallChan <- call
		resp := <-call.ResponseChan
		if resp.Type == "panic" {
			panic(resp.PanicValue)
		}

		var result1 error
		if len(resp.ReturnValues) > 0 {
			if value, ok := resp.ReturnValues[0].(error); ok {
				result1 = value
			}
		}

		return result1
	}
	return h
}
