// Code generated by impgen. DO NOT EDIT.
// impgen:hash:b6a9e249d45fb2fc

package mockfunction_test

import (
	context "context"
	_imptest "github.com/toejough/imptest"
	mockfunction "github.com/toejough/imptest/UAT/core/mock-function"
)

// ProcessOrderMockArgs holds typed arguments for ProcessOrder.
type ProcessOrderMockArgs struct {
	Ctx     context.Context
	OrderID int
}

// ProcessOrderMockCall wraps DependencyCall with typed GetArgs and Return.
type ProcessOrderMockCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ProcessOrderMockCall) GetArgs() ProcessOrderMockArgs {
	raw := c.RawArgs()
	return ProcessOrderMockArgs{
		Ctx:     raw[0].(context.Context),
		OrderID: raw[1].(int),
	}
}

// Return specifies the typed values the mock should return.
func (c *ProcessOrderMockCall) Return(result0 *mockfunction.Order, result1 error) {
	c.DependencyCall.Return(result0, result1)
}

// ProcessOrderMockMethod wraps DependencyMethod with typed returns.
type ProcessOrderMockMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *ProcessOrderMockMethod
}

// Expect waits for a call with exactly the specified arguments.
func (m *ProcessOrderMockMethod) Expect(ctx context.Context, orderID int) *ProcessOrderMockCall {
	call := m.DependencyMethod.Expect(ctx, orderID)
	return &ProcessOrderMockCall{DependencyCall: call}
}

// Match waits for a call with arguments matching the given matchers.
func (m *ProcessOrderMockMethod) Match(matchers ...any) *ProcessOrderMockCall {
	call := m.DependencyMethod.Match(matchers...)
	return &ProcessOrderMockCall{DependencyCall: call}
}

// MockProcessOrder creates a mock ProcessOrder function and returns (mock, expectation handle).
func MockProcessOrder(t _imptest.TestReporter) (func(ctx context.Context, orderID int) (*mockfunction.Order, error), *ProcessOrderMockMethod) {
	ctrl := _imptest.GetOrCreateImp(t)
	imp := newProcessOrderMockMethod(_imptest.NewDependencyMethod(ctrl, "ProcessOrder"))
	mock := func(ctx context.Context, orderID int) (*mockfunction.Order, error) {
		call := &_imptest.GenericCall{
			MethodName:   "ProcessOrder",
			Args:         []any{ctx, orderID},
			ResponseChan: make(chan _imptest.GenericResponse, 1),
		}
		ctrl.CallChan <- call
		resp := <-call.ResponseChan
		if resp.Type == "panic" {
			panic(resp.PanicValue)
		}

		var result1 *mockfunction.Order
		if len(resp.ReturnValues) > 0 {
			if value, ok := resp.ReturnValues[0].(*mockfunction.Order); ok {
				result1 = value
			}
		}

		var result2 error
		if len(resp.ReturnValues) > 1 {
			if value, ok := resp.ReturnValues[1].(error); ok {
				result2 = value
			}
		}

		return result1, result2
	}
	return mock, imp
}

// newProcessOrderMockMethod creates a typed method wrapper with Eventually initialized.
func newProcessOrderMockMethod(dm *_imptest.DependencyMethod) *ProcessOrderMockMethod {
	m := &ProcessOrderMockMethod{DependencyMethod: dm}
	m.Eventually = &ProcessOrderMockMethod{DependencyMethod: dm.Eventually}
	return m
}
