// Code generated by impgen. DO NOT EDIT.

package samepackage_test

import (
	samepackage "github.com/toejough/imptest/UAT/14-same-package-interfaces"
	_imptest "github.com/toejough/imptest/imptest"
)

// DataSinkMock is the mock for DataSink.
type DataSinkMock struct {
	imp     *_imptest.Imp
	PutData *_imptest.DependencyMethod
}

// Interface returns the DataSink implementation that can be passed to code under test.
func (m *DataSinkMock) Interface() samepackage.DataSink {
	return &mockDataSinkImpl{mock: m}
}

// MockDataSink creates a new DataSinkMock for testing.
func MockDataSink(t _imptest.TestReporter) *DataSinkMock {
	imp := _imptest.NewImp(t)
	return &DataSinkMock{
		imp:     imp,
		PutData: _imptest.NewDependencyMethod(imp, "PutData"),
	}
}

// mockDataSinkImpl implements samepackage.DataSink.
type mockDataSinkImpl struct {
	mock *DataSinkMock
}

// PutData implements samepackage.DataSink.PutData.
func (impl *mockDataSinkImpl) PutData(data []byte) error {
	call := &_imptest.GenericCall{
		MethodName:   "PutData",
		Args:         []any{data},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
