// Code generated by impgen. DO NOT EDIT.

package samepackage_test

import (
	samepackage "github.com/toejough/imptest/UAT/14-same-package-interfaces"
	_imptest "github.com/toejough/imptest/imptest"
)

// DataSourceMock is the mock for DataSource.
type DataSourceMock struct {
	imp     *_imptest.Imp
	GetData *_imptest.DependencyMethod
}

// Interface returns the DataSource implementation that can be passed to code under test.
func (m *DataSourceMock) Interface() samepackage.DataSource {
	return &mockDataSourceImpl{mock: m}
}

// DataSourceMockGetDataCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type DataSourceMockGetDataCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *DataSourceMockGetDataCall) InjectReturnValues(result0 []byte, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// MockDataSource creates a new DataSourceMock for testing.
func MockDataSource(t _imptest.TestReporter) *DataSourceMock {
	imp := _imptest.NewImp(t)
	return &DataSourceMock{
		imp:     imp,
		GetData: _imptest.NewDependencyMethod(imp, "GetData"),
	}
}

// mockDataSourceImpl implements samepackage.DataSource.
type mockDataSourceImpl struct {
	mock *DataSourceMock
}

// GetData implements samepackage.DataSource.GetData.
func (impl *mockDataSourceImpl) GetData() ([]byte, error) {
	call := &_imptest.GenericCall{
		MethodName:   "GetData",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 []byte
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].([]byte); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}
