// Code generated by impgen. DO NOT EDIT.
// impgen:hash:cab20a4fe5f16fc8

package channels_test

import (
	_imptest "github.com/toejough/imptest"
	channels "github.com/toejough/imptest/UAT/variations/signature/channels"
)

// ChannelHandlerMockBidirectionalArgs holds typed arguments for Bidirectional.
type ChannelHandlerMockBidirectionalArgs struct {
	Ch chan bool
}

// ChannelHandlerMockBidirectionalCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ChannelHandlerMockBidirectionalCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ChannelHandlerMockBidirectionalCall) GetArgs() ChannelHandlerMockBidirectionalArgs {
	raw := c.RawArgs()
	return ChannelHandlerMockBidirectionalArgs{
		Ch: raw[0].(chan bool),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ChannelHandlerMockBidirectionalCall) InjectReturnValues(result0 bool) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ChannelHandlerMockBidirectionalMethod wraps DependencyMethod with typed returns.
type ChannelHandlerMockBidirectionalMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *ChannelHandlerMockBidirectionalMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ChannelHandlerMockBidirectionalMethod) ExpectCalledWithExactly(ch chan bool) *ChannelHandlerMockBidirectionalCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(ch)
	return &ChannelHandlerMockBidirectionalCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ChannelHandlerMockBidirectionalMethod) ExpectCalledWithMatches(matchers ...any) *ChannelHandlerMockBidirectionalCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ChannelHandlerMockBidirectionalCall{DependencyCall: call}
}

// ChannelHandlerMockHandle is the test handle for ChannelHandler.
type ChannelHandlerMockHandle struct {
	Mock       channels.ChannelHandler
	Method     *ChannelHandlerMockMethods
	Controller *_imptest.Imp
}

// ChannelHandlerMockMethods holds method wrappers for setting expectations.
type ChannelHandlerMockMethods struct {
	SendOnly      *ChannelHandlerMockSendOnlyMethod
	ReceiveOnly   *ChannelHandlerMockReceiveOnlyMethod
	Bidirectional *ChannelHandlerMockBidirectionalMethod
	ReturnChannel *_imptest.DependencyMethod
}

// ChannelHandlerMockReceiveOnlyArgs holds typed arguments for ReceiveOnly.
type ChannelHandlerMockReceiveOnlyArgs struct {
	Ch <-chan string
}

// ChannelHandlerMockReceiveOnlyCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ChannelHandlerMockReceiveOnlyCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ChannelHandlerMockReceiveOnlyCall) GetArgs() ChannelHandlerMockReceiveOnlyArgs {
	raw := c.RawArgs()
	return ChannelHandlerMockReceiveOnlyArgs{
		Ch: raw[0].(<-chan string),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ChannelHandlerMockReceiveOnlyCall) InjectReturnValues(result0 string, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// ChannelHandlerMockReceiveOnlyMethod wraps DependencyMethod with typed returns.
type ChannelHandlerMockReceiveOnlyMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *ChannelHandlerMockReceiveOnlyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ChannelHandlerMockReceiveOnlyMethod) ExpectCalledWithExactly(ch <-chan string) *ChannelHandlerMockReceiveOnlyCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(ch)
	return &ChannelHandlerMockReceiveOnlyCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ChannelHandlerMockReceiveOnlyMethod) ExpectCalledWithMatches(matchers ...any) *ChannelHandlerMockReceiveOnlyCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ChannelHandlerMockReceiveOnlyCall{DependencyCall: call}
}

// ChannelHandlerMockReturnChannelCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ChannelHandlerMockReturnChannelCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ChannelHandlerMockReturnChannelCall) InjectReturnValues(result0 <-chan int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ChannelHandlerMockSendOnlyArgs holds typed arguments for SendOnly.
type ChannelHandlerMockSendOnlyArgs struct {
	Ch chan<- int
}

// ChannelHandlerMockSendOnlyCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ChannelHandlerMockSendOnlyCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ChannelHandlerMockSendOnlyCall) GetArgs() ChannelHandlerMockSendOnlyArgs {
	raw := c.RawArgs()
	return ChannelHandlerMockSendOnlyArgs{
		Ch: raw[0].(chan<- int),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ChannelHandlerMockSendOnlyCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ChannelHandlerMockSendOnlyMethod wraps DependencyMethod with typed returns.
type ChannelHandlerMockSendOnlyMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *ChannelHandlerMockSendOnlyMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ChannelHandlerMockSendOnlyMethod) ExpectCalledWithExactly(ch chan<- int) *ChannelHandlerMockSendOnlyCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(ch)
	return &ChannelHandlerMockSendOnlyCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ChannelHandlerMockSendOnlyMethod) ExpectCalledWithMatches(matchers ...any) *ChannelHandlerMockSendOnlyCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ChannelHandlerMockSendOnlyCall{DependencyCall: call}
}

// MockChannelHandler creates a new ChannelHandlerMockHandle for testing.
func MockChannelHandler(t _imptest.TestReporter) *ChannelHandlerMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &ChannelHandlerMockMethods{
		SendOnly:      newChannelHandlerMockSendOnlyMethod(_imptest.NewDependencyMethod(ctrl, "SendOnly")),
		ReceiveOnly:   newChannelHandlerMockReceiveOnlyMethod(_imptest.NewDependencyMethod(ctrl, "ReceiveOnly")),
		Bidirectional: newChannelHandlerMockBidirectionalMethod(_imptest.NewDependencyMethod(ctrl, "Bidirectional")),
		ReturnChannel: _imptest.NewDependencyMethod(ctrl, "ReturnChannel"),
	}
	h := &ChannelHandlerMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockChannelHandlerImpl{handle: h}
	return h
}

// mockChannelHandlerImpl implements channels.ChannelHandler.
type mockChannelHandlerImpl struct {
	handle *ChannelHandlerMockHandle
}

// Bidirectional implements channels.ChannelHandler.Bidirectional.
func (impl *mockChannelHandlerImpl) Bidirectional(ch chan bool) bool {
	call := &_imptest.GenericCall{
		MethodName:   "Bidirectional",
		Args:         []any{ch},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 bool
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(bool); ok {
			result1 = value
		}
	}

	return result1
}

// ReceiveOnly implements channels.ChannelHandler.ReceiveOnly.
func (impl *mockChannelHandlerImpl) ReceiveOnly(ch <-chan string) (string, error) {
	call := &_imptest.GenericCall{
		MethodName:   "ReceiveOnly",
		Args:         []any{ch},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// ReturnChannel implements channels.ChannelHandler.ReturnChannel.
func (impl *mockChannelHandlerImpl) ReturnChannel() <-chan int {
	call := &_imptest.GenericCall{
		MethodName:   "ReturnChannel",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 <-chan int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(<-chan int); ok {
			result1 = value
		}
	}

	return result1
}

// SendOnly implements channels.ChannelHandler.SendOnly.
func (impl *mockChannelHandlerImpl) SendOnly(ch chan<- int) error {
	call := &_imptest.GenericCall{
		MethodName:   "SendOnly",
		Args:         []any{ch},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// newChannelHandlerMockBidirectionalMethod creates a typed method wrapper with Eventually initialized.
func newChannelHandlerMockBidirectionalMethod(dm *_imptest.DependencyMethod) *ChannelHandlerMockBidirectionalMethod {
	m := &ChannelHandlerMockBidirectionalMethod{DependencyMethod: dm}
	m.Eventually = &ChannelHandlerMockBidirectionalMethod{DependencyMethod: dm.Eventually}
	return m
}

// newChannelHandlerMockReceiveOnlyMethod creates a typed method wrapper with Eventually initialized.
func newChannelHandlerMockReceiveOnlyMethod(dm *_imptest.DependencyMethod) *ChannelHandlerMockReceiveOnlyMethod {
	m := &ChannelHandlerMockReceiveOnlyMethod{DependencyMethod: dm}
	m.Eventually = &ChannelHandlerMockReceiveOnlyMethod{DependencyMethod: dm.Eventually}
	return m
}

// newChannelHandlerMockSendOnlyMethod creates a typed method wrapper with Eventually initialized.
func newChannelHandlerMockSendOnlyMethod(dm *_imptest.DependencyMethod) *ChannelHandlerMockSendOnlyMethod {
	m := &ChannelHandlerMockSendOnlyMethod{DependencyMethod: dm}
	m.Eventually = &ChannelHandlerMockSendOnlyMethod{DependencyMethod: dm.Eventually}
	return m
}
