// Code generated by impgen. DO NOT EDIT.

package functype_test

import (
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapWalkFuncCallHandle represents a single call to the wrapped function.
type WrapWalkFuncCallHandle struct {
	*_imptest.CallableController[WrapWalkFuncReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapWalkFuncCallHandleEventually
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapWalkFuncCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapWalkFuncCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (h *WrapWalkFuncCallHandle) ExpectReturnsEqual(v0 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapWalkFuncCallHandle) ExpectReturnsMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapWalkFuncCallHandleEventually wraps a call handle for async expectation registration.
type WrapWalkFuncCallHandleEventually struct {
	h *WrapWalkFuncCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapWalkFuncCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapWalkFuncCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapWalkFuncCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapWalkFuncReturnsReturn holds the return values from the wrapped function.
type WrapWalkFuncReturnsReturn struct {
	Result0 error
}

// WrapWalkFuncWrapperHandle is the test handle for a wrapped function.
type WrapWalkFuncWrapperHandle struct {
	Method     *WrapWalkFuncWrapperMethod
	Controller *_imptest.TargetController
}

// WrapWalkFuncWrapperMethod wraps a function for testing.
type WrapWalkFuncWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(string, string) error
}

// Start executes the wrapped function in a goroutine.
func (m *WrapWalkFuncWrapperMethod) Start(path string, info string) *WrapWalkFuncCallHandle {
	handle := &WrapWalkFuncCallHandle{
		CallableController: _imptest.NewCallableController[WrapWalkFuncReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapWalkFuncCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := m.callable(path, info)
		handle.ReturnChan <- WrapWalkFuncReturnsReturn{Result0: ret0}
	}()
	return handle
}

// WrapWalkFunc wraps a function for testing.
func WrapWalkFunc(t _imptest.TestReporter, fn func(string, string) error) *WrapWalkFuncWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapWalkFuncWrapperHandle{
		Method: &WrapWalkFuncWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
