// Code generated by impgen. DO NOT EDIT.

package handlers_test

import (
	context "context"
	handlers "github.com/toejough/imptest/UAT/core/wrapper-interface"
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
	"testing"
)

// WrapLoggerWrapperHandle wraps an implementation of handlers.Logger to intercept method calls.
type WrapLoggerWrapperHandle struct {
	Method *WrapLoggerWrapperMethods
	impl   handlers.Logger
}

// WrapLoggerWrapperLogCallHandle represents a single call to the wrapped method.
type WrapLoggerWrapperLogCallHandle struct {
	*_imptest.CallableController[WrapLoggerWrapperLogReturns]
}

// ExpectCompletes verifies the method completes without panicking.
func (h *WrapLoggerWrapperLogCallHandle) ExpectCompletes() {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		h.T.Fatalf("expected method to complete, but it panicked with: %v", h.Panicked)
	}
}

// ExpectPanicEquals verifies the method panics with the expected value.
func (h *WrapLoggerWrapperLogCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected method to panic, but it returned")
}

// ExpectPanicMatches verifies the method panics with a value matching the given matcher.
func (h *WrapLoggerWrapperLogCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected method to panic, but it returned")
}

// ExpectReturnsEqual verifies the method returned the expected values.
func (h *WrapLoggerWrapperLogCallHandle) ExpectReturnsEqual(v0 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected method to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapLoggerWrapperLogCallHandle) ExpectReturnsMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected method to return, but it panicked with: %v", h.Panicked)
}

type WrapLoggerWrapperLogReturns struct {
	Result0 error
}

// WrapLoggerWrapperLogWithContextCallHandle represents a single call to the wrapped method.
type WrapLoggerWrapperLogWithContextCallHandle struct {
	*_imptest.CallableController[WrapLoggerWrapperLogWithContextReturns]
}

// ExpectCompletes verifies the method completes without panicking.
func (h *WrapLoggerWrapperLogWithContextCallHandle) ExpectCompletes() {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		h.T.Fatalf("expected method to complete, but it panicked with: %v", h.Panicked)
	}
}

// ExpectPanicEquals verifies the method panics with the expected value.
func (h *WrapLoggerWrapperLogWithContextCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected method to panic, but it returned")
}

// ExpectPanicMatches verifies the method panics with a value matching the given matcher.
func (h *WrapLoggerWrapperLogWithContextCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected method to panic, but it returned")
}

// ExpectReturnsEqual verifies the method returned the expected values.
func (h *WrapLoggerWrapperLogWithContextCallHandle) ExpectReturnsEqual(v0 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected method to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapLoggerWrapperLogWithContextCallHandle) ExpectReturnsMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected method to return, but it panicked with: %v", h.Panicked)
}

type WrapLoggerWrapperLogWithContextReturns struct {
	Result0 error
}

type WrapLoggerWrapperLogWithContextWrapper struct {
	t  *testing.T
	fn func(ctx context.Context, msg string) WrapLoggerWrapperLogWithContextReturns
}

// Start executes the wrapped method in a goroutine.
func (w *WrapLoggerWrapperLogWithContextWrapper) Start(ctx context.Context, msg string) *WrapLoggerWrapperLogWithContextCallHandle {
	handle := &WrapLoggerWrapperLogWithContextCallHandle{
		CallableController: _imptest.NewCallableController[WrapLoggerWrapperLogWithContextReturns](w.t),
	}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		returns := w.fn(ctx, msg)
		handle.ReturnChan <- returns
	}()
	return handle
}

type WrapLoggerWrapperLogWrapper struct {
	t  *testing.T
	fn func(msg string) WrapLoggerWrapperLogReturns
}

// Start executes the wrapped method in a goroutine.
func (w *WrapLoggerWrapperLogWrapper) Start(msg string) *WrapLoggerWrapperLogCallHandle {
	handle := &WrapLoggerWrapperLogCallHandle{
		CallableController: _imptest.NewCallableController[WrapLoggerWrapperLogReturns](w.t),
	}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		returns := w.fn(msg)
		handle.ReturnChan <- returns
	}()
	return handle
}

// WrapLoggerWrapperMethods holds method wrappers for all intercepted methods.
type WrapLoggerWrapperMethods struct {
	Log            *WrapLoggerWrapperLogWrapper
	LogWithContext *WrapLoggerWrapperLogWithContextWrapper
}

// WrapLogger creates a new wrapper for the given handlers.Logger implementation.
func WrapLogger(t *testing.T, impl handlers.Logger) *WrapLoggerWrapperHandle {
	h := &WrapLoggerWrapperHandle{
		impl:   impl,
		Method: &WrapLoggerWrapperMethods{},
	}
	h.Method.Log = wrapWrapLoggerWrapperLog(t, func(msg string) WrapLoggerWrapperLogReturns {
		r0 := h.impl.Log(msg)
		return WrapLoggerWrapperLogReturns{Result0: r0}
	})
	h.Method.LogWithContext = wrapWrapLoggerWrapperLogWithContext(t, func(ctx context.Context, msg string) WrapLoggerWrapperLogWithContextReturns {
		r0 := h.impl.LogWithContext(ctx, msg)
		return WrapLoggerWrapperLogWithContextReturns{Result0: r0}
	})
	return h
}

func wrapWrapLoggerWrapperLog(t *testing.T, fn func(msg string) WrapLoggerWrapperLogReturns) *WrapLoggerWrapperLogWrapper {
	return &WrapLoggerWrapperLogWrapper{t: t, fn: fn}
}

func wrapWrapLoggerWrapperLogWithContext(t *testing.T, fn func(ctx context.Context, msg string) WrapLoggerWrapperLogWithContextReturns) *WrapLoggerWrapperLogWithContextWrapper {
	return &WrapLoggerWrapperLogWithContextWrapper{t: t, fn: fn}
}
