// Code generated by impgen. DO NOT EDIT.

package embeddedstructs_test

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// TimedLoggerMockHandle is the test handle for TimedLogger.
type TimedLoggerMockHandle struct {
	Mock       TimedLoggerMockInterface
	Method     *TimedLoggerMockMethods
	Controller *_imptest.Imp
}

// TimedLoggerMockIncCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TimedLoggerMockIncCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TimedLoggerMockIncCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// TimedLoggerMockInterface is a generated interface matching the methods of TimedLogger.
type TimedLoggerMockInterface interface {
	Inc() int
	Log(msg string) string
	LogWithCount(msg string) string
	SetPrefix(prefix string)
	Value() int
}

// TimedLoggerMockLogArgs holds typed arguments for Log.
type TimedLoggerMockLogArgs struct {
	Msg string
}

// TimedLoggerMockLogCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TimedLoggerMockLogCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TimedLoggerMockLogCall) GetArgs() TimedLoggerMockLogArgs {
	raw := c.RawArgs()
	return TimedLoggerMockLogArgs{
		Msg: raw[0].(string),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TimedLoggerMockLogCall) InjectReturnValues(result0 string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// TimedLoggerMockLogMethod wraps DependencyMethod with typed returns.
type TimedLoggerMockLogMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *TimedLoggerMockLogMethod) Eventually() *TimedLoggerMockLogMethod {
	return &TimedLoggerMockLogMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *TimedLoggerMockLogMethod) ExpectCalledWithExactly(msg string) *TimedLoggerMockLogCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(msg)
	return &TimedLoggerMockLogCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *TimedLoggerMockLogMethod) ExpectCalledWithMatches(matchers ...any) *TimedLoggerMockLogCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &TimedLoggerMockLogCall{DependencyCall: call}
}

// TimedLoggerMockLogWithCountArgs holds typed arguments for LogWithCount.
type TimedLoggerMockLogWithCountArgs struct {
	Msg string
}

// TimedLoggerMockLogWithCountCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TimedLoggerMockLogWithCountCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TimedLoggerMockLogWithCountCall) GetArgs() TimedLoggerMockLogWithCountArgs {
	raw := c.RawArgs()
	return TimedLoggerMockLogWithCountArgs{
		Msg: raw[0].(string),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TimedLoggerMockLogWithCountCall) InjectReturnValues(result0 string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// TimedLoggerMockLogWithCountMethod wraps DependencyMethod with typed returns.
type TimedLoggerMockLogWithCountMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *TimedLoggerMockLogWithCountMethod) Eventually() *TimedLoggerMockLogWithCountMethod {
	return &TimedLoggerMockLogWithCountMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *TimedLoggerMockLogWithCountMethod) ExpectCalledWithExactly(msg string) *TimedLoggerMockLogWithCountCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(msg)
	return &TimedLoggerMockLogWithCountCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *TimedLoggerMockLogWithCountMethod) ExpectCalledWithMatches(matchers ...any) *TimedLoggerMockLogWithCountCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &TimedLoggerMockLogWithCountCall{DependencyCall: call}
}

// TimedLoggerMockMethods holds method wrappers for setting expectations.
type TimedLoggerMockMethods struct {
	Inc          *_imptest.DependencyMethod
	Log          *TimedLoggerMockLogMethod
	LogWithCount *TimedLoggerMockLogWithCountMethod
	SetPrefix    *TimedLoggerMockSetPrefixMethod
	Value        *_imptest.DependencyMethod
}

// TimedLoggerMockSetPrefixArgs holds typed arguments for SetPrefix.
type TimedLoggerMockSetPrefixArgs struct {
	Prefix string
}

// TimedLoggerMockSetPrefixCall wraps DependencyCall with typed GetArgs.
type TimedLoggerMockSetPrefixCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TimedLoggerMockSetPrefixCall) GetArgs() TimedLoggerMockSetPrefixArgs {
	raw := c.RawArgs()
	return TimedLoggerMockSetPrefixArgs{
		Prefix: raw[0].(string),
	}
}

// TimedLoggerMockSetPrefixMethod wraps DependencyMethod with typed returns.
type TimedLoggerMockSetPrefixMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *TimedLoggerMockSetPrefixMethod) Eventually() *TimedLoggerMockSetPrefixMethod {
	return &TimedLoggerMockSetPrefixMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *TimedLoggerMockSetPrefixMethod) ExpectCalledWithExactly(prefix string) *TimedLoggerMockSetPrefixCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(prefix)
	return &TimedLoggerMockSetPrefixCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *TimedLoggerMockSetPrefixMethod) ExpectCalledWithMatches(matchers ...any) *TimedLoggerMockSetPrefixCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &TimedLoggerMockSetPrefixCall{DependencyCall: call}
}

// TimedLoggerMockValueCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TimedLoggerMockValueCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TimedLoggerMockValueCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// MockTimedLogger creates a new TimedLoggerMockHandle for testing.
func MockTimedLogger(t _imptest.TestReporter) *TimedLoggerMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &TimedLoggerMockMethods{
		Inc:          _imptest.NewDependencyMethod(ctrl, "Inc"),
		Log:          &TimedLoggerMockLogMethod{DependencyMethod: _imptest.NewDependencyMethod(ctrl, "Log")},
		LogWithCount: &TimedLoggerMockLogWithCountMethod{DependencyMethod: _imptest.NewDependencyMethod(ctrl, "LogWithCount")},
		SetPrefix:    &TimedLoggerMockSetPrefixMethod{DependencyMethod: _imptest.NewDependencyMethod(ctrl, "SetPrefix")},
		Value:        _imptest.NewDependencyMethod(ctrl, "Value"),
	}
	h := &TimedLoggerMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockTimedLoggerImpl{handle: h}
	return h
}

// mockTimedLoggerImpl implements TimedLoggerMockInterface.
type mockTimedLoggerImpl struct {
	handle *TimedLoggerMockHandle
}

// Inc implements TimedLogger.Inc.
func (impl *mockTimedLoggerImpl) Inc() int {
	call := &_imptest.GenericCall{
		MethodName:   "Inc",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// Log implements TimedLogger.Log.
func (impl *mockTimedLoggerImpl) Log(msg string) string {
	call := &_imptest.GenericCall{
		MethodName:   "Log",
		Args:         []any{msg},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}

// LogWithCount implements TimedLogger.LogWithCount.
func (impl *mockTimedLoggerImpl) LogWithCount(msg string) string {
	call := &_imptest.GenericCall{
		MethodName:   "LogWithCount",
		Args:         []any{msg},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}

// SetPrefix implements TimedLogger.SetPrefix.
func (impl *mockTimedLoggerImpl) SetPrefix(prefix string) {
	call := &_imptest.GenericCall{
		MethodName:   "SetPrefix",
		Args:         []any{prefix},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// Value implements TimedLogger.Value.
func (impl *mockTimedLoggerImpl) Value() int {
	call := &_imptest.GenericCall{
		MethodName:   "Value",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}
