// Code generated by impgen. DO NOT EDIT.
// impgen:hash:c3e4576a3e28ec00

package funclit_test

import (
	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

// StartFilterCallHandle represents a single call to the wrapped function.
type StartFilterCallHandle struct {
	*_imptest.CallableController[StartFilterReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *StartFilterCallHandleEventually
}

// ExpectPanic verifies the function panics with the expected value.
func (h *StartFilterCallHandle) ExpectPanic(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatch verifies the function panics with a value matching the given matcher.
func (h *StartFilterCallHandle) ExpectPanicMatch(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturn verifies the function returned the expected values.
func (h *StartFilterCallHandle) ExpectReturn(v0 []int) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnMatch verifies the return values match the given matchers.
func (h *StartFilterCallHandle) ExpectReturnMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// StartFilterCallHandleEventually wraps a call handle for async expectation registration.
type StartFilterCallHandleEventually struct {
	h *StartFilterCallHandle
}

// ExpectPanic registers an async expectation for a panic value.
func (e *StartFilterCallHandleEventually) ExpectPanic(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ExpectReturn registers an async expectation for return values.
func (e *StartFilterCallHandleEventually) ExpectReturn(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *StartFilterCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// StartFilterReturnsReturn holds the return values from the wrapped function.
type StartFilterReturnsReturn struct {
	Result0 []int
}

// StartFilter starts the wrapped function in a goroutine for testing.
func StartFilter(t _imptest.TestReporter, fn func([]int, func(int) bool) []int, items []int, predicate func(int) bool) *StartFilterCallHandle {
	handle := &StartFilterCallHandle{
		CallableController: _imptest.NewCallableController[StartFilterReturnsReturn](t),
		controller:         _imptest.NewTargetController(t),
	}
	handle.Eventually = &StartFilterCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := fn(items, predicate)
		handle.ReturnChan <- StartFilterReturnsReturn{Result0: ret0}
	}()
	return handle
}
