// Code generated by impgen. DO NOT EDIT.

package funclit_test

import (
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapExecutorRunCallHandle represents a single call to the wrapped function.
type WrapExecutorRunCallHandle struct {
	*_imptest.CallableController[WrapExecutorRunReturnsReturn]
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapExecutorRunCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapExecutorRunCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (h *WrapExecutorRunCallHandle) ExpectReturnsEqual(v0 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapExecutorRunCallHandle) ExpectReturnsMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapExecutorRunReturnsReturn holds the return values from the wrapped function.
type WrapExecutorRunReturnsReturn struct {
	Result0 error
}

// WrapExecutorRunWrapper wraps a function for testing.
type WrapExecutorRunWrapper struct {
	t        _imptest.TestReporter
	callable func(func() error) error
}

// Start executes the wrapped function in a goroutine.
func (w *WrapExecutorRunWrapper) Start(callback func() error) *WrapExecutorRunCallHandle {
	handle := &WrapExecutorRunCallHandle{
		CallableController: _imptest.NewCallableController[WrapExecutorRunReturnsReturn](w.t),
	}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := w.callable(callback)
		handle.ReturnChan <- WrapExecutorRunReturnsReturn{Result0: ret0}
	}()
	return handle
}

// WrapExecutorRun wraps a function for testing.
func WrapExecutorRun(t _imptest.TestReporter, fn func(func() error) error) *WrapExecutorRunWrapper {
	return &WrapExecutorRunWrapper{
		t:        t,
		callable: fn,
	}
}
