// Code generated by impgen. DO NOT EDIT.
// impgen:hash:e1950d14e3c09a8b

package funclit_test

import (
	_imptest "github.com/toejough/imptest"
	_reflect "reflect"
)

// WrapFilterCallHandle represents a single call to the wrapped function.
type WrapFilterCallHandle struct {
	*_imptest.CallableController[WrapFilterReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapFilterCallHandleEventually
}

// ExpectPanic verifies the function panics with the expected value.
func (h *WrapFilterCallHandle) ExpectPanic(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatch verifies the function panics with a value matching the given matcher.
func (h *WrapFilterCallHandle) ExpectPanicMatch(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturn verifies the function returned the expected values.
func (h *WrapFilterCallHandle) ExpectReturn(v0 []int) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnMatch verifies the return values match the given matchers.
func (h *WrapFilterCallHandle) ExpectReturnMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapFilterCallHandleEventually wraps a call handle for async expectation registration.
type WrapFilterCallHandleEventually struct {
	h *WrapFilterCallHandle
}

// ExpectPanic registers an async expectation for a panic value.
func (e *WrapFilterCallHandleEventually) ExpectPanic(value any) {
	e.ensureStarted().ExpectPanic(value)
}

// ExpectReturn registers an async expectation for return values.
func (e *WrapFilterCallHandleEventually) ExpectReturn(values ...any) {
	e.ensureStarted().ExpectReturn(values...)
}

func (e *WrapFilterCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapFilterReturnsReturn holds the return values from the wrapped function.
type WrapFilterReturnsReturn struct {
	Result0 []int
}

// WrapFilterWrapperHandle is the test handle for a wrapped function.
type WrapFilterWrapperHandle struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func([]int, func(int) bool) []int
}

// Start executes the wrapped function in a goroutine.
func (w *WrapFilterWrapperHandle) Start(items []int, predicate func(int) bool) *WrapFilterCallHandle {
	handle := &WrapFilterCallHandle{
		CallableController: _imptest.NewCallableController[WrapFilterReturnsReturn](w.t),
		controller:         w.controller,
	}
	handle.Eventually = &WrapFilterCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := w.callable(items, predicate)
		handle.ReturnChan <- WrapFilterReturnsReturn{Result0: ret0}
	}()
	return handle
}

// WrapFilter wraps a function for testing.
func WrapFilter(t _imptest.TestReporter, fn func([]int, func(int) bool) []int) *WrapFilterWrapperHandle {
	return &WrapFilterWrapperHandle{
		t:          t,
		controller: _imptest.NewTargetController(t),
		callable:   fn,
	}
}
