// Code generated by "stringer -type ActivityType"; DO NOT EDIT.

package imptest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActivityTypeUnset-0]
	_ = x[ActivityTypeReturn-1]
	_ = x[ActivityTypePanic-2]
	_ = x[ActivityTypeCall-3]
}

const _ActivityType_name = "ActivityTypeUnsetActivityTypeReturnActivityTypePanicActivityTypeCall"

var _ActivityType_index = [...]uint8{0, 17, 35, 52, 68}

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityType_index)-1) {
		return "ActivityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActivityType_name[_ActivityType_index[i]:_ActivityType_index[i+1]]
}
